### ISSUE TITLE
StandardCharsets crashes on Android API < 19.

### ISSUE THREAD

**Issue by Thomas-Vos** [eclipse/californium#567] opened 2018-03-04 16:42 UTC
This library uses `java.nio.charset.StandardCharsets` in multiple places. This class was added in Android API 19, so it won't work on older versions. If I use Californium on Android API <19 it crashes with the following error:

    java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets

I manually copied the `java.nio.charset.StandardCharsets` file into my project and then Californium works without any issues.

Changing all usages of this Java class to `Charset.forName(...)` instead of the static constants will fix this crash for Android API <19. Is this something that could be changed in Californium?

See the following for all usages of this class: https://github.com/eclipse/californium/search?q=StandardCharsets

**Comment by boaks** [comment] 2018-03-05 08:40
> I manually copied the java.nio.charset.StandardCharsets file into my project and then Californium works without any issues.

Did you check "plain" coap, or also with "DTLS" coaps?

My oldest device to test is API 19, and frequently we run into "encryption" issues, which hard to solve and would be much harder to solve without test-device.

**Comment by Thomas-Vos** [comment] 2018-03-05 09:00
@boaks I tested it with DTLS. I'm using version 2.0.0-M6 with `californium-core` and `scandium` modules. Apart from this missing class, I haven't run into any other issues yet on API 16.

**Comment by boaks** [comment] 2018-03-05 09:03
Cool, I prepare a fix.

**Comment by boaks** [comment] 2018-03-05 11:55
@Thomas-Vos 

If possible, checkout the PR #568 and verify, if it works for you.

**Comment by Thomas-Vos** [comment] 2018-03-05 19:21
I tested the pull request, after I removed the copied StandardCharsets file from my project, on Android API 16. It now works correctly without any issues. I left one comment on the pull request. Thank you very much for the fast support!

**Comment by boaks** [comment] 2018-03-06 19:26
Discussing the PR I remembered, that I changed the minSdkVersion from 15 to 19 because `System.lineSeparator()` is used but marked with API 19. So are you sure, that this doesn't cause issues using older android versions?

**Comment by Thomas-Vos** [comment] 2018-03-06 19:42
Looks like another thing that might need to be changed. This definitely won't work below API 19. A quick search in this library showed that `System.lineSeparator()` is mostly used in tests and `toString()` methods. I am not calling the `toString()` methods of the Californium library anywhere in my project, so that explains why I haven't run into this issue yet. So yes, this might cause issues depending on how someone uses Californium.

**Comment by sbernard31** [comment] 2018-03-07 13:30
I find a way to check API level compatibility with maven.
(see #570)
I played a bit with it and it seems we are compatible with API 19.
I checked with API 16 and I faced this issues :
```
element-connector:
String java.net.InetSocketAddress.getHostString()

element-connector-tcp :
String java.net.InetSocketAddress.getHostString()

scandium : 
String System.lineSeparator()
java.nio.charset.Charset java.nio.charset.StandardCharsets.US_ASCII
java.nio.charset.Charset java.nio.charset.StandardCharsets.UTF_8

Californium core : 
void Throwable.addSuppressed(Throwable)
java.nio.charset.Charset java.nio.charset.StandardCharsets.UTF_8
String java.net.InetSocketAddress.getHostString()
System.lineSeparator()
```

**Comment by boaks** [comment] 2018-03-08 08:29
FMPOV I would still merge #568 because it fixes the reported issues.
Though I don't plan to really support below API 19, I don't feel that hard about the additional violations.
@Thomas-Vos 
So, do you think #568 is still useful for you?

**Comment by sbernard31** [comment] 2018-03-08 13:12
> FMPOV I would still merge #568 because it fixes the reported issues.

Ok but what is the point if we don't target API below 19. I feel that strange to just fix this partially.

Here is a list of what I guess it does not works (probably not exhaustive) : 
- load and store network config (because of addSuppressed)
- coapEndpoint destroy() (because of getURi => getHoststring())
- trying to start an already coapEndpoint or stop an already stop endpoint ( because of getURi => getHoststring)
- EndpointManager.getDefaultEndpoint(String) which is used for Request.send ( because of getHoststring)
- scandium should not works because of lineSeparator (mainly in DTLSSession.setReadState)
- element-connector-tcp should not works because of getHostString(when we create SSLEngine)
- lot of tostring which is difficult to guess where they are used (because of lineSeparator)

> Though I don't plan to really support below API 19, I don't feel that hard about the additional violations.

- We already have a fix for `Charsets`.
- `System.lineSeparator` should be replace by creating a class which use System.getProperty("line.separator") @Thomas-Vos  do you know if it works on android ?
- `getHostString` will be more problematic, I do not know easy way to replace it without triggering a name service reverse lookup.
- `Throwable.addSuppressed` means no more `Try-with-resource` :cry:

**Comment by Thomas-Vos** [comment] 2018-03-08 20:57
@boaks Yes, the pull request will still be useful for me. This is because the pull request does fix Californium for me on API 16. This is probably because I don't call the toString() methods anywhere, so that explains why I haven't run into the `System.lineSeparator` issue, yet. I really do not want to drop support for API 16-18 if possible because I still have quite some active users on those Android versions.

I agree with @sbernard31 that it is strange to just add support for API 16+ partially. I think it is best to fix some more points on the list to ensure that Californium works correctly on API 16+.

@sbernard31 `System.getProperty("line.separator")` will work on Android. If we are going to change this it is probably best to put it somewhere in a static variable for performance. Furthermore, a search shows that all `Try-with-resource` usage is in tests, demo apps, and 2 places within `NetworkConfig.java`. This one should be very easy to change.

**Comment by boaks** [comment] 2018-03-09 08:48
I'm not sure, if the "try-with-resource" is really used with android.
It's related to `File`. I use the `NetworkConfig` either based on Assets (and then the `InputStream`) or "in code configuration".

**Comment by boaks** [comment] 2018-04-02 18:31
So FMPOV, in the meantime it looks like 
- document the NetworkConfig, 
- changing the lineSeparator and 
- not using element-connector-tcp for old androids 

should fix this issue. But still be aware:
I don't have such old devices so only reported issues with (small) fixes could obeyed and in cases of real solution conflicts, it maybe not possible to make it working for older android version ;-(.

**Comment by boaks** [comment] 2018-04-10 14:53
FMPOV, I now use californium for a android apps for about 6 month. My oldest device is Android 4.4, a newer is 5.0. My errors are all caused not by "API" incompatibility (detectable by the check plugin), they have been caused by different implementations! Cloning the `Mac` failed, using the "AES" Cipher behaves different and required to be "AES/ECB/NoPadding". So my concern with that is:
I can't check, if the implementations is really working on older android versions!
Therefore it seems for me to be more honest, to support 4.4 (and test that), then to promise support for older versions, where I can only check the API, and not, if californium is working.
Therefore I can change the findings of others (as long as this is possible), but I can't "grant", that it is or will work on older android versions.

**Comment by sbernard31** [comment] 2018-04-10 15:41
I'm ok we can not "grant" there are no runtime incompatibility, but if you start to make effort to support a given level API,  It seems to me that checking static API compatibility is a minimal requirement.

**Comment by sbernard31** [comment] 2018-04-12 08:04
> I got deeper into the "animal" stuff and tried the "annotation" filter by adding a "NotForAndroid" 

:+1:

I could propose a PR.

**Comment by boaks** [comment] 2018-04-12 08:47
Though my plans for this morning has change, I update the PR und pushed it right now.

**Comment by boaks** [comment] 2018-04-12 18:04
@Thomas-Vos 

The PR is merged to 2.0.x. It would be cool, if you can also test with API 16+.
If find any issue, don't hesitate to create either a new issue or add a comment here.

**Closed by boaks** 2018-04-12 18:04 UTC

**Comment by Thomas-Vos** [comment] 2018-07-23 19:43
Hello, I've been quite busy with other stuff but finally had the time to test the new version. I can confirm version 2.0.0-M11 works correctly on Android API 16. Thank you very much for the pull request!

**Comment by boaks** [comment] 2018-07-24 07:14
Great! Thanks for testing.

**Comment by boaks** [comment] 2021-02-08 09:30
@Thomas-Vos 

I currently work on Californium 3.0 and some code-cleanup. Are you still using/supporting Android API 16+ ?

**Comment by Thomas-Vos** [comment] 2021-02-08 09:38
No, I now only support Android API 21+. I am also using "Java 8+ APIs available through desugaring" on Android.

**Comment by boaks** [comment] 2021-02-08 09:50
Thanks for the fast answer!

Just to mention: currently I work on the "graceful-dtls- restart". Over the weekend I managed to update my own android-advanced-app to use this feature also for the client side. Together with DTLS CID, that makes handshakes to be an issue of the past and left only for unclear ip-connectivity.
I hope, end of the month it's stable enough to consider a 3.0.0-M1 release.

**Comment by Thomas-Vos** [comment] 2021-02-10 13:56
Seems interesting, I will check it out once the build is available.

Great to see that you did not forget this issue, I really appreciate it.

**Comment by boaks** [comment] 2021-02-10 14:12
You're welcome.

And cool to know, that you still using it. Without too much trouble, I hope :-).

**Comment by Thomas-Vos** [comment] 2021-03-29 14:12
> And cool to know, that you still using it. Without too much trouble, I hope :-).

I am using this library in my app Hue Essentials for the IKEA gateway. Californium makes that really easy.

However, upgrading can be a bit challenging sometimes. I am using R8 for code obfuscation in my Android app. I need to fix the rules after upgrading Californium most of the times.

**Comment by boaks** [comment] 2021-03-29 14:15
> I need to fix the rules after upgrading Californium most of the times.

I guess, that's caused by renaming stuff, right? 
Or is there any other cause, I'm not aware of?

**Comment by Thomas-Vos** [comment] 2021-03-29 14:18
Yes, that is right. R8 renames, removes, and moves, classes and functions. Most libraries I use have R8 rules included or do not need them as they are not using reflection.

**Comment by boaks** [comment] 2021-03-29 14:23
So, is this limited to stuff, which is used via "reflection" by Californium itself?

**Comment by Thomas-Vos** [comment] 2021-03-29 17:04
I created an issue with some more details here: https://github.com/eclipse/californium/issues/1583. I removed the rules in my project that are no longer needed, and there are two left that are required. One of them is Californium code, the other is slf4j code.
