### ISSUE TITLE
Make layer stack of CoAP endpoint customizable

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#439] opened 2017-10-13 15:16 UTC
My first need is to have access to BlockwiseLayer to check memory leak.
But I think this could be useful to be able to customize the coapstack of an endpoint.

I imagine to add protected methods  `createUdpStack` and `createTcpStack` which could be overridden to use a custom stack. Why not a parameters to constructors ? It's possible but we begin to have lot of parameters in constructors and a lot of constructors in CoapEndpoint.

The second point is to make easier to choose layer implementation in udp/tcp stack.
Two solutions :
1) add also protected "create" method for each layer
2) just pass each layer as arguments (null == default one)

This is optional because without that, it is still possible to create your own stack with your own layers  but I think you will often change only one layer.

Any opinion ?

**Comment by boaks** [comment] 2017-10-13 15:31
FMPOV we currently debugging and want to check different ideas. For that it seems a good deal. 
But I'm not sure, if I understand, how you intend to do it.

**Comment by sbernard31** [comment] 2017-10-13 15:56
For the first point, something like this : 

```java
CoapEndpoint ep = new CoAPEndpoint() {
       protected CoapStack createUdpStack(NetworkConfig config, Outbox outbox){
               return new MyCustomUdpStack(config,outbox);
       }
}
```

**Comment by boaks** [comment] 2017-10-13 16:04
Maybe, this feature could be added with issue #198 
(Or at least a clean up of the constructors :-) ).

**Comment by sbernard31** [comment] 2017-10-13 16:29
If we add a builder, we will need something like a CoapStackFactory as coapstack constructor need some arguments (config and outbox). Maybe somethink like we do in https://github.com/eclipse/leshan/issues/372#issuecomment-325592364 ?

(I hope the fact that the leshan example use coapendpoint is not so confusing :/)

**Comment by danielhqv** [comment] 2017-10-29 09:48
This sounds exactly like what I'm interested in as well, but in my case it's for simulation purposes on the client. I would like to inject my own custom BlockwiseLayer to be able to simulate block transfer latency and other unexpected behavior in a controlled way.

**Comment by boaks** [comment] 2017-10-30 07:58
That feature is already merged to 2.0.x (see PR #449, commit 5bf7e90e3da839e4758b1235ad721e502fd3258f in 2.0.x)

@sbernard31 
Is it possible, that you close this issue?

**Comment by boaks** [comment] 2017-10-30 08:01
https://github.com/eclipse/californium/issues/439#issuecomment-340249511

The CoAP stack is, as far as I understand it, not intended to delay message processing. I'm not sure, if that will cause more issues than expected.
In branch 2.0.x we have also a small NAT util. Depending on your requirements, this would allow to delay "unspecific all" messages for some time.

**Comment by boaks** [comment] 2017-11-03 11:45
@sbernard31 

Is there something left for this issue?
Or can we close it?

**Closed** 2017-11-03 13:23 UTC
Labels: waiting for feedback
