### ISSUE TITLE
Have more information about the foreign peer in logs.

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#1298] opened 2020-04-27 08:24 UTC
It would great to have more information about the foreign peer in logs (Initially needed for scandium but maybe it makes sense on californium too)

In Scandium, the idea could to use `connection.toString` each time it's possible (instead of just peer address), but for now `connection.toString` does not show the peer identity (e.g. PSK id or Public key)

It could be added to the current `toString` OR/AND  a new interface could be created to allow user to print information they need.

Personally, my guess is `peer address` + `conId` + `sessionId` + `peerIdentity` should cover most of the use case, so maybe the interface is not really needed.

(This issue was created from the discussion in : https://github.com/eclipse/californium/issues/1284)

**Comment by boaks** [comment] 2020-05-16 08:13
For me it seems to be worth to check, if [MDC](http://www.slf4j.org/manual.html#mdc), e.g. introduce a "PEER" and load it with the proper information, would solve this evene a little more general.

So it would require some "volunteers" to investigate on that. I assume, I will not be able to spend my time into that for the next week (may be months).

**Comment by AndreasMager** [comment] 2020-06-18 12:26
We have some trouble with debugging scandium connections too.
Adding a `session id` to the log lines would enhance debugging of dtls connections.

I have played with your MDC approach in the org.eclipse.californium.scandium.dtls.Handshaker. 
MDC is a static resource for the current running thread. It must be filled and cleaned on each thread change.
If we add more Key/Value pairs for peer, conId & peerIdenty to MDC it becomes even more complicated.

All code sections with importance should be changed to this:
`
MDCCloseable closeMe = fillMDC();
try {
  processMessage(record) 
} finally {
 closeMe.close();
}`

It is not an easy task to figure the right spots for these changes.

Refactoring all log lines and add a "connection.toString" seems to be easier approach.

**Comment by boaks** [comment] 2020-06-18 18:10
Thanks for your feedback.

My idea was to provide the peer's information in "callbacks" for the `SerialExecutor` of the `Connection` (means: if the serial executer starts a job in `scheduleNextJob()`, there will be a callback to set the MDC, and a callback to clean it. Or something similar).

Beside of that, threads are only rarely assigned to peers:
Incoming: protected void processDatagram(DatagramPacket packet)
Outgoing: public final void send(final RawData message)

FMPOV, that should be not that big issue.

> We have some trouble with debugging scandium connections too.

Any trouble to report? Any found bugs?

**Comment by AndreasMager** [comment] 2020-06-22 09:50
I will take a deeper dive in the code and give you feedback. 

> Any trouble to report? Any found bugs?

We haven't found any bugs yet. 
A low precentage(<10%) of devices has connection problems.
The cause can be on every part of the system (Client, Mobile Provider or Scandium).

**Comment by boaks** [comment] 2020-06-22 13:41
If it make it easier for you, I prepare a PR for the `SerialExecutor` and the `Connection` to setup the MDC.

**Comment by AndreasMager** [comment] 2020-06-22 16:18
Thanks @boaks i have found the code places.
It should work now.
I want test it with my setup but have some struggle with the gradle/maven snapshot mess.
When i have fixed and verified it i will create a PR.

**Comment by boaks** [comment] 2020-06-25 07:15
@sbernard31 

If possible, please check, if PR #1347 with the MDC "works for you".
After that PR it would be possible to "cleanup" some logging messages and that may cause a couple of changed lines. So I would prefer to check the MDC usage before.

**Comment by sbernard31** [comment] 2020-06-25 13:11
Done (see https://github.com/eclipse/californium/pull/1347#pullrequestreview-437448077)

**Comment by boaks** [comment] 2020-07-20 05:59
Any reasons to keep this open?

**Closed** 2020-07-21 06:38 UTC
Labels: could this be closed?, enhancement
