### ISSUE TITLE
OSCORE Pre-shared Key 

### ISSUE THREAD

**Issue by eliot4321** [eclipse/californium#1301] opened 2020-05-02 17:07 UTC
Hi,

I can see that in the OSCORE  example you are assuming that the keys are pre-shared "Following the OSCORE RFC".  However, the first request sent from an OSCORE client within the same session it's always taking too long than other following requests(for example 500 ms first request, 
 20 to 30  ms the following ones). Could you please explain the reason behind this behavior? 

Thanks in advance

**Comment by boaks** [comment] 2020-05-03 09:24
What is your network setup?
Intranet?
Internet?  
Could you check the times using "plain coap", no DTLS and no OSCORE?

**Comment by eliot4321** [comment] 2020-05-03 13:46
Two nodes one machine running. the oscore server and one machine running the oscore client, both they in the same private WLAN network provided as a hotspot by the server machine,  to have a clean network.

The first request within CoAP is normal as the others.

**Comment by eliot4321** [comment] 2020-05-03 15:24
Hi,
A clarification:  Should the first OScore request behave as the consecutive requests?

Thanks

**Comment by onovo1** [comment] 2020-05-04 06:01
Hi,

I got similar results. The first OSCORE request really takes very long time. I have tested it in my own Intranet. Is there any configuration setup to improve this performance?

**Comment by boaks** [comment] 2020-05-04 06:23
@rikard-sics 

Do you have any guess about that?

**Comment by rikard-sics** [comment] 2020-05-04 09:18
Hello.

Thank you both for reporting this issue. I need to investigate further to understand why this is happening and if something is taking long in the code for the first request. There is nothing in inherent in OSCORE itself (like a handshake) that should slow down the first request.

May I ask if you also experience these issues when having the OSCORE-stack enabled with _OSCoreCoapStackFactory.useAsDefault(db)_ but then sending the messages as CoAP-only messages (without adding the OSCORE option)?

I have tried running some tests of my own and I do see a slowdown for the first request (around 100 ms compared to 2 ms for the following messages). For CoAP-only I see around 30 ms for the first request versus 1 ms for the rest.

(I also realize now that the getRTT() method does not work on responses when using OSCORE. I will fix this in a future PR.)

**Comment by eliot4321** [comment] 2020-05-04 09:47
Hi,

I tried after disabling the OSCORE option and I'm still getting latency on the first request, even I have other comments that the following requests took 15 ms in average  on running in localhost that's is quite high value.

**Comment by rikard-sics** [comment] 2020-05-04 09:54
Thanks for the quick follow-up.

> I tried after disabling the OSCORE option and I'm still getting latency on the first request.
I have another question: the following requests took 15 ms "quite high value" on average while running in localhost?

I see. Do you get this latency both when using _OSCoreCoapStackFactory.useAsDefault(db)_ and not?

**Comment by eliot4321** [comment] 2020-05-04 10:01
Without using the OSCoreCoapStackFactory.useAsDefault(db), the latency of the first request dropped to 75 ms on average,  but it's still higher for the consecutive requests.

**Comment by rikard-sics** [comment] 2020-05-04 10:41
> Without using the OSCoreCoapStackFactory.useAsDefault(db), the latency of the first request dropped to 75 ms on average, but it's still higher for the consecutive requests.
> The response CODE is: 4.02 Failed to decode cose.

Make sure to turn off the stack on both client & server.

To get a better overview of the different scenarios, could you run some tests and fill out the following table with the average round trip times?

|    |  OSCORE Stack & OSCORE option  | OSCORE Stack & no OSCORE option | Standard Stack & OSCORE option | Standard Stack & no OSCORE option |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| **First Request**  | X ms | X ms | X ms | X ms |
| **Other Requests**  | X ms | X ms | X ms | X ms |

**Comment by eliot4321** [comment] 2020-05-04 11:29
|  | OSCORE Stack & OSCORE option | OSCORE Stack & no OSCORE option | Standard Stack & OSCORE option | Standard Stack & no OSCORE option |
| -- | -- | -- | -- | -- |
| first request | 448  ms | 86 ms | 89 ms | 77 ms |
| other request | 20  ms | 9 ms | 11 ms | 8 ms |
|  Response Text |   Hellowrold | ----   |  HelloWorld |   --- |
| Response Code |  Content 2.05 | 4.01 unauthorized | Content 2.05  | 4.01 unauthorized |

**Comment by rikard-sics** [comment] 2020-05-04 11:52
Thanks a lot for the results.  I assume you are using the HelloWorldServer and client? Could you try changing all (4) instances of OSCoreResource to CoapResource in the HelloWorldServer? And then try measuring again? That should make it so the requests work in all cases.

**Comment by eliot4321** [comment] 2020-05-04 12:09
I updated the previous table you can check the new values.

**Comment by boaks** [comment] 2020-05-04 12:37
Just to mention:
Java does a lot, when code is executed the 1. time.
To overcome such effects, please don't stop the server.
Start even a 2. server (different port) and adapt the client to send the 1. request to that 2. server and then measure the rtt with a 2. request to the 1. server. Repeat that without restarting the servers. I guess in the 2. round you will get results, which differs less.

**Comment by eliot4321** [comment] 2020-05-04 18:19
@boaks  thanks for the tips. Unfortunately, it didn't work getting replay detected error.

**Comment by boaks** [comment] 2020-05-04 18:26
For plain coap without oscore it may be helpfull to see, that this is just caused by the java runtime.

**Comment by rikard-sics** [comment] 2020-05-05 09:38
> I updated the previous table you can check the new values.

Thanks for the updated values.

I will try to do more tests regarding this. One thing I want to test is the following:
Have context A and B.
Client: Send request 1 with context A
Server: Process request 1 with context A
Client: Send request 2 with context B
Server: Process request 2 with context B

So the question is if it is generally the first message that takes longer or if it is the first message for a particular context that takes longer.

**Comment by eliot4321** [comment] 2020-05-06 13:41
Hi @rikard-sics ,

How  to send a request with a specific context.

Thanks

**Comment by rikard-sics** [comment] 2020-05-06 19:30
I have now implemented and performed some more tests.

For the code see HelloWorldServer/HelloWorldServerContext and HelloWorldClient/HelloWorldClientContext at the following link: https://github.com/rikard-sics/californium/tree/oscore_rtt_test

**5 requests using CoAP followed by 5 requests using OSCORE**
Client output:
Request 0: Hello World! (47 ms) (using OSCORE: false)
Request 1: Hello World! (1 ms) (using OSCORE: false)
Request 2: Hello World! (1 ms) (using OSCORE: false)
Request 3: Hello World! (1 ms) (using OSCORE: false)
Request 4: Hello World! (1 ms) (using OSCORE: false)
Request 5: Hello World! (116 ms) (using OSCORE: true)
Request 6: Hello World! (3 ms) (using OSCORE: true)
Request 7: Hello World! (3 ms) (using OSCORE: true)
Request 8: Hello World! (2 ms) (using OSCORE: true)
Request 9: Hello World! (5 ms) (using OSCORE: true)

So clearly the first OSCORE request sent there incurs extra latency even if it is not the first request sent overall. Switching back and forth between OSCORE and CoAP it seems it's always the first (singular) OSCORE message that takes extra time.

**5 requests using OSCORE with context A followed by 5 requests using OSCORE with context B**
Client output:
Request 0: Hello World! (174 ms) (using OSCORE: true. With context: AAAAAAAA)
Request 1: Hello World! (5 ms) (using OSCORE: true. With context: AAAAAAAA)
Request 2: Hello World! (2 ms) (using OSCORE: true. With context: AAAAAAAA)
Request 3: Hello World! (2 ms) (using OSCORE: true. With context: AAAAAAAA)
Request 4: Hello World! (2 ms) (using OSCORE: true. With context: AAAAAAAA)
Request 5: Hello World! (2 ms) (using OSCORE: true. With context: BBBBBBBB)
Request 6: Hello World! (4 ms) (using OSCORE: true. With context: BBBBBBBB)
Request 7: Hello World! (4 ms) (using OSCORE: true. With context: BBBBBBBB)
Request 8: Hello World! (3 ms) (using OSCORE: true. With context: BBBBBBBB)
Request 9: Hello World! (3 ms) (using OSCORE: true. With context: BBBBBBBB)

Switching to a different context does not seem to incur any extra overhead.

I will continue investigating this.

> Hi @rikard-sics ,
> 
> In the second request, I got a "replay detect" error

Hi. I saw your previous post about switching contexts too. Check the HelloWorldClientContext & HelloWorldServerContext for one way this can be done in. Basically on the client the existing context needs to be replaced with the new one in the context DB.

**Comment by boaks** [comment] 2020-05-06 19:36
Let me try it again:
Java does a lot, when code is executed the 1. time. That is no bug, that is common.
So does the times change, if you keep the server running but run the client a second time?

**Comment by rikard-sics** [comment] 2020-05-06 19:46
> Let me try it again:
> Java does a lot, when code is executed the 1. time. That is no bug, that is common.
> So does the times change, if you keep the server running but run the client a second time?

Thanks for the feedback. I tried the test you are suggesting. Keeping the server running for 10 requests and running the client twice with 5 requests for each run.

**Client run 1:**
Request 0: Hello World! (171 ms) (using OSCORE: true)
Request 1: Hello World! (10 ms) (using OSCORE: true)
Request 2: Hello World! (3 ms) (using OSCORE: true)
Request 3: Hello World! (2 ms) (using OSCORE: true)
Request 4: Hello World! (3 ms) (using OSCORE: true)

**Client run 2:**
Request 0: Hello World! (87 ms) (using OSCORE: true)
Request 1: Hello World! (7 ms) (using OSCORE: true)
Request 2: Hello World! (3 ms) (using OSCORE: true)
Request 3: Hello World! (3 ms) (using OSCORE: true)
Request 4: Hello World! (3 ms) (using OSCORE: true)

The latency for first message in the 2nd run seems less on average than the first message in the first run.

**Same experiment with CoAP only:**
**Client run 1:**
Request #0: Hello World! (63 ms) (using OSCORE: false)
Request #1: Hello World! (2 ms) (using OSCORE: false)
Request #2: Hello World! (1 ms) (using OSCORE: false)
Request #3: Hello World! (1 ms) (using OSCORE: false)
Request #4: Hello World! (1 ms) (using OSCORE: false)

**Client run 2:**
Request #0: Hello World! (30 ms) (using OSCORE: false)
Request #1: Hello World! (2 ms) (using OSCORE: false)
Request #2: Hello World! (1 ms) (using OSCORE: false)
Request #3: Hello World! (3 ms) (using OSCORE: false)
Request #4: Hello World! (1 ms) (using OSCORE: false)

**Comment by boaks** [comment] 2020-05-07 05:44
> So perhaps it could be due to Java initialization as you suggest?

looks like :-).

**Comment by onovo1** [comment] 2020-05-07 05:59
@rikard-sics @boaks thank you to check this!

Indeed, it seems the Java initialization creates some latency. 
However, shouldn't the first OSCORE request have the same latency than the consecutive requests? I am wondering what is created such a latency if both nodes are using pre-shared keys.

**Comment by boaks** [comment] 2020-05-07 06:03
> Indeed, it seems the Java initialization creates some latency.

I would guess, some "Crypto.getInstance(algo)" calls.

**Comment by onovo1** [comment] 2020-05-07 06:08
> > Indeed, it seems the Java initialization creates some latency.
> 
> I would guess, some "Crypto.getInstance(algo)" calls.

My understanding is that the client and server use hardcoded keys. They are not randomly generated, right?

**Comment by boaks** [comment] 2020-05-07 06:16
> My understanding is that the client and server use hardcoded keys. They are not randomly generated, right?

That is not related to e.g. `Cipher.getInstance("AES/ECB/NoPadding")`.

**Comment by onovo1** [comment] 2020-05-07 06:25
> 
> That is not related to e.g. `Cipher.getInstance("AES/ECB/NoPadding")`.

Yes, that is true.  
However, the encryption and decryption functions should be used in all requests, not only in the first one, right? Thus, the latency should be the same in all the requests.
I am missing something here but I can't figure out what it is. :/

**Comment by boaks** [comment] 2020-05-07 06:29
Scandium uses [ThreadLocalCipher](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/ThreadLocalCipher.java). That will initialize a cipher only once per thread.
There maybe additional and other explanations. But I have my doubts, if this investigation pays off. Wee will see ...

**Comment by onovo1** [comment] 2020-05-07 06:34
> Scandium uses [ThreadLocalCipher](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/ThreadLocalCipher.java). That will initialize a cipher only once per thread.

OK, that makes sense.

**Comment by boaks** [comment] 2020-05-07 06:55
You are welcome!

**Comment by eliot4321** [comment] 2020-05-07 07:04
Hi,
Thanks @boaks ,
It seems the thread could cause the problem. But, I'm still wondering if the latency in the CoAP first request is caused by the same Thread as  CoAP doesn't have any security process so the ThreadLocalCipher should not be created for CoAP.

**Comment by rikard-sics** [comment] 2020-05-07 10:21
> Scandium uses [ThreadLocalCipher](https://github.com/eclipse/californium/blob/master/scandium-core/src/main/java/org/eclipse/californium/scandium/dtls/cipher/ThreadLocalCipher.java). That will initialize a cipher only once per thread.
> There maybe additional and other explanations. But I have my doubts, if this investigation pays off. Wee will see ...

Yeah and OSCORE uses the crypto functions from Scandium. So it could definitively be cipher initialization.

From my latest test, with keeping the server running, the RTT for the first request in the 2nd run of the client has lower RTT (looks like about half). So in that test the server only has to initialize the ciphers once, but the client does it for both of its runs. So somehow it can be consistent that the RTT is halved in the 2nd run of the client (since the server ciphers is already initialized then).


**Initializing the ciphers at client/server startup**

I tried a basic test to initialize the ciphers at startup for the server and client by adding the following at the start of the main methods in HelloWorldClient and HelloWorldServer:
```
String CIPHER_NAME = "AES/ECB/NoPadding";
ThreadLocalCipher CIPHER = new ThreadLocalCipher(CIPHER_NAME);
Cipher test = CIPHER.current();
System.out.println(test.getProvider());
```
Then I get the following results.

Client output:
Request 0: Hello World! (59 ms) (using OSCORE: false)
Request 1: Hello World! (1 ms) (using OSCORE: false)
Request 2: Hello World! (1 ms) (using OSCORE: false)
Request 3: Hello World! (5 ms) (using OSCORE: false)
Request 4: Hello World! (2 ms) (using OSCORE: false)
Request 5: Hello World! (37 ms) (using OSCORE: true)
Request 6: Hello World! (3 ms) (using OSCORE: true)
Request 7: Hello World! (3 ms) (using OSCORE: true)
Request 8: Hello World! (4 ms) (using OSCORE: true)
Request 9: Hello World! (3 ms) (using OSCORE: true)

**Comment by onovo1** [comment] 2020-05-07 10:36
> I'm still wondering if the latency in the CoAP first request is caused by the same Thread as CoAP doesn't have any security process so the ThreadLocalCipher should not be created for CoAP.

That's a good point. What is creating that latency of 30ms in CoAP?

**Comment by boaks** [comment] 2020-05-07 11:03
> What is creating that latency of 30ms in CoAP?

I assume, that's a mixture of several reasons. One was the crypto initialization.
A other reason maybe "java jit compiler optimizations".

**Comment by onovo1** [comment] 2020-05-07 11:41
> I assume, that's a mixture of several reasons. One was the crypto initialization.

But the CoAP scenario doesnt use the crypto functions, right?

**Comment by boaks** [comment] 2020-05-07 11:44
> But the CoAP scenario doesnt use the crypto functions, right?

yes. But it maybe affected by the other reason, the "java jit compiler optimizations".

**Comment by boaks** [comment] 2020-05-20 11:08
Does someone still work on finding the root-cause for the initial delay?
For me, this is caused by java. So I would prefer to close this issue.

**Comment by rikard-sics** [comment] 2020-05-20 11:10
> Does someone still work on finding the root-cause for the initial delay?
> For me, this is caused by java. So I would prefer to close this issue.

One point that seems relevant for OSCORE is the allocation of the crypto algorithms. It seems it is causing extra latency for the first request sent or received.

I had a discussion in a meeting with Ericsson regarding this point. What do you think about initializing the crypto algorithms already when the OSCORE context object is created? That way we do that ahead of time and not upon reception/transmission of a request.

**Comment by boaks** [comment] 2020-05-20 11:33
That initialization is required per thread. So I'm not sure, if this makes sense.

**Comment by rikard-sics** [comment] 2020-05-20 11:43
> That initialization is required per thread. So I'm not sure, if this makes sense.

Yes I was not sure so I was planning to bring this up.

I noticed in my experiments above that if I initialize the cipher it in the beginning of the application code I see reduced latency for the first request. It would be great to be able to do this automatically for applications so they can avoid the initial latency when using OSCORE.

Typically the OSCORE context will be created in the application code. So that's why I was thinking to do it there. But perhaps there are issues regarding multiple threads as you say? Would it make more sense to have a static method somewhere that an application can call to initialize the ciphers (and call itself) or would that have the same problems?

For an application receiving requests, will the thread set to handle them change throughout the course of its runtime? If it is the same it would be enough to initialize the cipher for that thread.

**Comment by boaks** [comment] 2020-05-20 11:57
Usually, the java ciphers (or other crypto functions) have state and are therefore not thread-safe. As long as multiple threads a used, the cipher function must be "cached" as thread locals. That's done in scandium. Sure you may do a "cold" call to the `CCMBlockCipher` and for that thread the cipher will be initialized. If that speeds up, OK:

**Comment by rikard-sics** [comment] 2020-05-20 12:27
> Usually, the java ciphers (or other crypto functions) have state and are therefore not thread-safe. As long as multiple threads a used, the cipher function must be "cached" as thread locals. That's done in scandium. Sure you may do a "cold" call to the `CCMBlockCipher` and for that thread the cipher will be initialized. If that speeds up, OK:

Thanks, I will try some experiments regarding this to see with which code and in which situations I gain a speedup.

So for instance when building an OSCORE context is it better if I call the CCMBlockCipher encrypt/decrypt with "empty values" to initialize things or use something like the following?
_String CIPHER_NAME = "AES/ECB/NoPadding";
ThreadLocalCipher CIPHER = new ThreadLocalCipher(CIPHER_NAME);
Cipher test = CIPHER.current();_
That should initialize the cipher for my current thread.

**Comment by boaks** [comment] 2020-05-20 13:11
For `CCMBlockCipher` just call `encrypt` there on dummy data.

```
String CIPHER_NAME = "AES/ECB/NoPadding";
ThreadLocalCipher CIPHER = new ThreadLocalCipher(CIPHER_NAME);
Cipher test = CIPHER.current();
```

That would only work, if that `CIPHER` is used by the same thread. For other threads or other `ThreadLocalCipher` instances, it will have no effect.

**Comment by rikard-sics** [comment] 2020-05-20 13:13
> For `CCMBlockCipher` just call `encrypt` there on dummy data.
> 
> ```
> String CIPHER_NAME = "AES/ECB/NoPadding";
> ThreadLocalCipher CIPHER = new ThreadLocalCipher(CIPHER_NAME);
> Cipher test = CIPHER.current();
> ```
> 
> That would only work, if that `CIPHER` is used by the same thread. For other threads or other `ThreadLocalCipher` instances, it will have no effect.

Thanks, I will try implementing this and see what speed results I get.

**Comment by rikard-sics** [comment] 2020-05-26 14:46
@onovo1 @eliot4321 I have now done a pull request with code to initialize the cipher object on creation of the OSCORE context. In that way it will be done ahead of time and not on encryption/decryption of the first request so this will reduce latency for it.

Could you perhaps try if you get better results after this modification?

Some results from basic testing I did:

### Using OSCORE from the start

**Before the change**
Request 0: Hello World! (RTT: **191**) (using OSCORE: true)
Request 1: Hello World! (RTT: 4) (using OSCORE: true)
Request 2: Hello World! (RTT: 4) (using OSCORE: true)
Request 3: Hello World! (RTT: 3) (using OSCORE: true)
Request 4: Hello World! (RTT: 3) (using OSCORE: true)
Request 5: Hello World! (RTT: 3) (using OSCORE: true)
Request 6: Hello World! (RTT: 3) (using OSCORE: true)
Request 7: Hello World! (RTT: 4) (using OSCORE: true)
Request 8: Hello World! (RTT: 4) (using OSCORE: true)
Request 9: Hello World! (RTT: 3) (using OSCORE: true)

**After the change**
Request 0: Hello World! (RTT: **73**) (using OSCORE: true)
Request 1: Hello World! (RTT: 5) (using OSCORE: true)
Request 2: Hello World! (RTT: 3) (using OSCORE: true)
Request 3: Hello World! (RTT: 3) (using OSCORE: true)
Request 4: Hello World! (RTT: 3) (using OSCORE: true)
Request 5: Hello World! (RTT: 3) (using OSCORE: true)
Request 6: Hello World! (RTT: 3) (using OSCORE: true)
Request 7: Hello World! (RTT: 3) (using OSCORE: true)
Request 8: Hello World! (RTT: 4) (using OSCORE: true)
Request 9: Hello World! (RTT: 3) (using OSCORE: true)

### Switching to OSCORE after 5 messages

**Before the change**
Request 0: Hello World! (RTT: 59) (using OSCORE: false)
Request 1: Hello World! (RTT: 1) (using OSCORE: false)
Request 2: Hello World! (RTT: 1) (using OSCORE: false)
Request 3: Hello World! (RTT: 1) (using OSCORE: false)
Request 4: Hello World! (RTT: 1) (using OSCORE: false)
Request 5: Hello World! (RTT: **135**) (using OSCORE: true)
Request 6: Hello World! (RTT: 3) (using OSCORE: true)
Request 7: Hello World! (RTT: 3) (using OSCORE: true)
Request 8: Hello World! (RTT: 3) (using OSCORE: true)
Request 9: Hello World! (RTT: 4) (using OSCORE: true)

**After the change**
Request 0: Hello World! (RTT: 53) (using OSCORE: false)
Request 1: Hello World! (RTT: 1) (using OSCORE: false)
Request 2: Hello World! (RTT: 1) (using OSCORE: false)
Request 3: Hello World! (RTT: 1) (using OSCORE: false)
Request 4: Hello World! (RTT: 1) (using OSCORE: false)
Request 5: Hello World! (RTT: **21**) (using OSCORE: true)
Request 6: Hello World! (RTT: 3) (using OSCORE: true)
Request 7: Hello World! (RTT: 3) (using OSCORE: true)
Request 8: Hello World! (RTT: 3) (using OSCORE: true)
Request 9: Hello World! (RTT: 3) (using OSCORE: true)

**Closed** 2020-06-24 14:49 UTC
Labels: could this be closed?, oscore
