### ISSUE TITLE
Reduce thread contention in CCMBlockCipher.decrypt

### ISSUE THREAD

**Issue by lhotari** [eclipse/californium#642] opened 2018-05-15 05:56 UTC
Californium version: 2.0.0-M9 (Leshan 1.0.0-M6)

Java Flight Recorder shows this stack trace as the top source of thread contention / blocking when running Leshan:
```
java.security.Provider.getService(String, String)
at sun.security.jca.ProviderList$ServiceList.tryGet(int)
at sun.security.jca.ProviderList$ServiceList.access$200(ProviderList$ServiceList, int)
at sun.security.jca.ProviderList$ServiceList$1.hasNext()
at javax.crypto.Cipher.getInstance(String)
at org.eclipse.californium.scandium.dtls.cipher.CCMBlockCipher.decrypt(byte[], byte[], byte[], byte[], int)
at org.eclipse.californium.scandium.dtls.Record.decryptAEAD(byte[], DTLSConnectionState)
at org.eclipse.californium.scandium.dtls.Record.decryptFragment(byte[], DTLSConnectionState)
at org.eclipse.californium.scandium.dtls.Record.decryptApplicationMessage(DTLSConnectionState)
at org.eclipse.californium.scandium.dtls.Record.getFragment(DTLSConnectionState)
at org.eclipse.californium.scandium.dtls.Record.getFragment()
at org.eclipse.californium.scandium.DTLSConnector.processApplicationDataRecord(Record)
at org.eclipse.californium.scandium.DTLSConnector.processRecord(Record)
at org.eclipse.californium.scandium.DTLSConnector.access$200(DTLSConnector, Record)
at org.eclipse.californium.scandium.DTLSConnector$2.run()
at eu.javaspecialists.tjsn.concurrency.stripedexecutor.StripedExecutorService$SerialExecutor$1.run()
```

It seems that the solution for mitigating this performance bottleneck is to pool `javax.crypto.Cipher` instances. Perhaps a simple ThreadLocal cache would be sufficient for this purpose.

**Comment by lhotari** [comment] 2018-05-15 05:58
Related JDK bug: https://bugs.openjdk.java.net/browse/JDK-7092821

**Comment by boaks** [comment] 2018-05-15 08:00
First, thank you very much for your analysis! 
I would really appreciate, if you could focus on the current 2.0.x branch, or even better on the PR #640, which I already created as fix for your other issue #637.

This issue, with `CCMBlockCipher.decrypt`, seems to be a duplicate of #609, which is fixed on the current 2.0.x. 

So, if it's possible that you verify the PR #640, then you should also be able to verify this issue as well.

**Comment by lhotari** [comment] 2018-05-15 08:41
@boaks Thanks for the quick reply once again. Yes this one is a duplicate of #609 and the fix for that one looked great. 
I'm currently busy on many things before my vacation so I might not be able to test #640 in my benchmark. Thanks for making that improvement, I'm sorry my testing feedback on that might go after my vacation.

**Closed** 2018-05-15 08:57 UTC
Labels: retest - validate PR

**Comment by boaks** [comment] 2018-05-15 08:58
Though I will be also on vacation from the next week on for two weeks,
I will still looking for you results after that :-).
