### ISSUE TITLE
randomly Null pointer exception while notify blockwise response under performance

### ISSUE THREAD

**Issue by joechen2010** [eclipse/californium#691] opened 2018-07-09 09:33 UTC
* branch your faced the issue. Currently 
   * and 2.0-M9
```
2018-07-09 11:52:28.199+08:00 ERROR 6f10b807-5204-4dad-8caa-4147a928153d  	 [CoapServer:5683#6] org.eclipse.californium.core.network.CoapEndpoint    {"TraceID":"6f10b807-5204-4dad-8caa-4147a928153d"} exception in protocol stage thread: null
java.lang.NullPointerException: null
        at org.eclipse.californium.elements.UdpEndpointContextMatcher.isResponseRelatedToRequest(UdpEndpointContextMatcher.java:70)
        at org.eclipse.californium.core.network.UdpMatcher.receiveResponse(UdpMatcher.java:249)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveResponse(CoapEndpoint.java:887)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:806)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:765)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:781)
        at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:1013)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2018-07-09 11:52:30.234+08:00 WARN 83e915dc-9bc3-4b0b-b238-1e847efe85ee 	 	 [CoapServer:5683#5] org.eclipse.californium.core.network.UdpMatcher {"TraceID":"83e915dc-9bc3-4b0b-b238-1e847efe85ee"} possible MID reuse before lifetime end for token [[cb1ccab9599a88a3]], expected MID 48851 but received 48850
2018-07-09 11:52:30.236+08:00 ERROR f55cbdd3-2cfe-4e4d-a594-f7c724114396 	 	 [CoapServer:5683#5] org.eclipse.californium.core.network.CoapEndpoint    {"TraceID":"f55cbdd3-2cfe-4e4d-a594-f7c724114396"} exception in protocol stage thread: null
java.lang.NullPointerException: null
2018-07-09 11:52:30.241+08:00 WARN 2f3de741-55f2-4bd2-9468-6834f6ae1096 	 	 [CoapServer:5683#3] org.eclipse.californium.core.network.UdpMatcher {"TraceID":"2f3de741-55f2-4bd2-9468-6834f6ae1096"} possible MID reuse before lifetime end for token [[3d98a24d28a25037]], expected MID 51137 but received 51136
2018-07-09 11:52:30.244+08:00 ERROR dcd32366-94f7-4b49-a4cb-1d1bd06c2b21 	 	 [CoapServer:5683#4] org.eclipse.californium.core.network.CoapEndpoint    {"TraceID":"dcd32366-94f7-4b49-a4cb-1d1bd06c2b21"} exception in protocol stage thread: null
2018-07-09 17:57:37.031+08:00 ERROR c762f8ec-bbe4-44c8-a01e-c500232d54ea  [CoapServer:5683#3] org.eclipse.californium.core.network.CoapEndpoint {"TraceID":"c762f8ec-bbe4-44c8-a01e-c500232d54ea"} exception in protocol stage thread: MID must be a 16 bit unsigned int: -1
java.lang.IllegalArgumentException: MID must be a 16 bit unsigned int: -1
        at org.eclipse.californium.core.network.Exchange$KeyMID.<init>(Exchange.java:669)
        at org.eclipse.californium.core.network.Exchange$KeyMID.fromOutboundMessage(Exchange.java:741)
        at org.eclipse.californium.core.network.UdpMatcher.receiveResponse(UdpMatcher.java:277)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveResponse(CoapEndpoint.java:887)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:806)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:765)
        at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:781)
        at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:1013)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by sbernard31** [comment] 2018-07-09 14:52
Could you give us more detail about how do reproduce this, or at least some context when this happened...

Did you implement your own ObservationStore ?

**Comment by boaks** [comment] 2018-07-09 14:57
> java.lang.NullPointerException: null
> at org.eclipse.californium.elements.UdpEndpointContextMatcher.isResponseRelatedToRequest(UdpEndpointContextMatcher.java:70)

seems to be caused by a null `requestContext`. 
In 2.0.0-M10 the calling function is changed to check the context before the isResponseRelatedToRequest is called:

```
EndpointContext context = exchange.getEndpointContext();
Request currentRequest = exchange.getCurrentRequest();
int requestMid = currentRequest.getMID();
if (context == null || requestMid == Message.NONE) {
	LOGGER.debug("ignoring response {}, request pending to sent!", response);
	return null;
}
```

So, please retest the behaviour with 2.0.0-M10.

**Comment by sbernard31** [comment] 2018-07-09 15:04
@boaks about null context,  any idea how this could happened. I believed that we always have a expected EndpointContext, the one created by Request.preparareDestination.

**Comment by boaks** [comment] 2018-07-09 15:17
`isResponseRelatedToRequest` use the context from the exchange, which is set by `onContextEstablished`, not the request's destination context, which may be a incomplete.
For plain upd, there is no difference, but, though the CoapEndpoint works for coap and coaps, the exchanges context must be used.

That together with "token reuse" for "observes" and "trackable blockwise" may cause such a null in case of some retransmissions. I also got such exceptions, therefore I added the null check prior to the `isResponseRelatedToRequest`.

**Comment by joechen2010** [comment] 2018-07-10 02:09
Hi, this happen only if the server under high performance load with blockwise notification

**Comment by boaks** [comment] 2018-07-10 07:43
> Hi, this happen only if the server under high performance load with blockwise notification

That was also my observation and therefore I add the check. So, if possible, please use 2.0.0-M10 for your tests and close this issue, if it doesn't occur with that milestone.

**Comment by boaks** [comment] 2018-07-18 07:58
@joechen2010 
If you still get such exceptions, don't hesitate to add a comment to this issue or create a new one.

**Closed by boaks** 2018-07-18 07:58 UTC
Labels: retest - validate PR
