### ISSUE TITLE
Is the Executor must be ScheduledExecutor ?

### ISSUE THREAD

**Issue by joechen2010** [eclipse/californium#690] opened 2018-07-06 03:53 UTC
I don't know why always ScheduledExecutor everywhere, especially coapendpoint, seems there is no schedule feature in it. in our test thread model (async http request with jetty and resteasy -> convert to coap request -> client coap resource)  seems there is performance issues with the jdk ScheduledThreadPoolExecutor, and i saw the BenchmarkServer also implements a customized ScheduledExecutorService, it means you have already found this defect, right?

**Comment by boaks** [comment] 2018-07-06 06:59
The executor is passed in the CoapStack and used to schedule retransmissions there in the ReliabilityLayer.

```
public void startTimer() {
	if (!exchange.isComplete()) {
		int timeout = exchange.getCurrentTimeout();
		ScheduledFuture<?> f = executor.schedule(this, timeout, TimeUnit.MILLISECONDS);
		exchange.setRetransmissionHandle(f);
	}
}
```

> and i saw the BenchmarkServer also implements a customized ScheduledExecutorService, it means you have already found this defect, right?

According git, that at least 3 years old and in the end, it uses also a ScheduledThreadPool.
 
```
public WorkQueueExecutor(int threads) {
	this(threads, Executors.newScheduledThreadPool(1));
}
```

But maybe @mkovatsc knows the reason.

If you do some performance test, can you post your results?
I'm wondering, if in your chain coap is really a bottleneck.
It may be possible, that especially for outgoing CON the ScheduledExecutor implementation spends too much time into it.

Do you use the CoapClient? Do you use "synchronous requests" (e.g. `CoapClient.get()`) ?
If so, try to use the "asynchronous request" (e.g. `CoapClient.get(CoapHandler handler)`). 

A second tip would be, to disable the deduplication,

```
// Network configuration optimal for performance benchmarks
NetworkConfig.createStandardWithoutFile()
	// Disable deduplication OR strongly reduce lifetime
	.setString(NetworkConfig.Keys.DEDUPLICATOR, NetworkConfig.Keys.NO_DEDUPLICATOR)
```

but FMPOV, in production this may have more drawbacks than benefits.

**Comment by joechen2010** [comment] 2018-07-06 07:38
Thanks Boaks, the result on our test with ScheduledThreadPoolExecutoris around 18k and the following executor is 35k. all outgoing type is CON, DEDUPLICATOR is disable, and the lifechange time was descred to 1500, also use asynchronous request like request.send(endpoint). 
if only ReliabilityLayer and observation require the ScheduledExecutor, maybe introduce another executor is better.
`
private static class Pool extends ScheduledThreadPoolExecutor{

        ExecutorService exe;
        public Pool(int corePoolSize, ThreadFactory threadFactory) {
            super(corePoolSize, threadFactory);
            // TODO Auto-generated constructor stub
            exe  = Executors.newFixedThreadPool(corePoolSize, threadFactory);
        }
        @Override
        public void execute(Runnable command) {
            // TODO Auto-generated method stub
            exe.execute(command);
        }
        
    }
`

**Comment by boaks** [comment] 2018-07-06 07:43
> ScheduledThreadPoolExecutoris around 18k and the following executor is 35k.

Impressive. I will consider to change that but it will take some time ...
You use plain coap without DTLS, or?

**Comment by joechen2010** [comment] 2018-07-06 07:45
no, it is no secure, dtls is worse.

**Comment by joechen2010** [comment] 2018-07-06 07:52
I guess the ScheduledThreadPoolExecutor is base on DelayedWorkQueue which is a heap-based data structure and  newFixedThreadPool is a LinkedBlockingQueue, i guress this is the reason, but i did not verify that.

**Comment by boaks** [comment] 2018-07-06 08:54
> dtls is worse.

Sure, it adds the complexity of crypto-functions.
FMPOV it is the base for offering CoAP in the internet/cloud and therefore I focus on the numbers for DTLS. But, if we can get some "low hanging food", I guess we will take it. 

Have you signed ECL (do you have the permission of your employer)?
Maybe you can contribute your Executor as "short cut to boost"?
If so, can you please check, if split the number of threads (1 for the scheduled, rest for the none-scheduled executor) works also? Though the numbers of threads are configurable, your solution will double that number of threads.

**Comment by joechen2010** [comment] 2018-07-06 09:31
yes, the threads will be double, I did check for that, but I have test with the your WorkQueueExecutor, the result is same as the Pool.
BTW, what's ECL, i do not get your point.

**Comment by sbernard31** [comment] 2018-07-06 09:40
Long time ago, I benchmarked several ThreadPoolExecutor using jmh and also find some performance gap but I don't now how much this is really impacting in "real world".
```
Benchmark                                             Mode  Cnt         Score           Error  Units
StripedExecutorBenchmark.testFixedExecutor           thrpt    3   4918507,203 ±   2343590,509  ops/s
StripedExecutorBenchmark.testScheduledExecutor       thrpt    3   1213638,419 ±  13751621,925  ops/s
StripedExecutorBenchmark.testSingleExecutor          thrpt    3   2992784,251 ±   2330399,721  ops/s
StripedExecutorBenchmark.testStripedExecutor         thrpt    3   1703791,932 ±  19345720,397  ops/s

```
I did some tests using `cf-extplugtest-server` an `cf-extplugtest-client` with or without your `Pool` class.

Here is my results :
```
Using ScheduledThreadPoolExecutor (plain coap, 500 clients, 1000 requests)
500 benchmark clients finished.
1000000 requests sent, 1000000 expected
1000000 requests in 49754ms, 20098 reqs/s
3840 retransmissions (0,38%)

Using "Pool" (plain coap, 500 clients, 1000 requests)
500 benchmark clients finished.
1000000 requests sent, 1000000 expected
1000000 requests in 45731ms, 21867 reqs/s
3163 retransmissions (0,32%)

Using "Pool with poolsize/2" (plain coap, 500 clients, 1000 requests)
500 benchmark clients finished.
1000000 requests sent, 1000000 expected
1000000 requests in 47035ms, 21260 reqs/s
3319 retransmissions (0,33%)

Using "Pool 1 thread for schedulor, poolsize/2 for others" (plain coap, 1000 clients, 1000 requests)
500 benchmark clients finished.
1000000 requests sent, 1000000 expected
1000000 requests in 44167ms, 22641 reqs/s
3047 retransmissions (0,30%)
-----------------------------------------

Using ScheduledThreadPoolExecutor (plain coap, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 99966ms, 20006 reqs/s
19468 retransmissions (0,97%)

Using "Pool" (plain coap, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 95246ms, 20998 reqs/s
17863 retransmissions (0,89%)

Using "Pool with poolsize/2" (plain coap, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 91435ms, 21873 reqs/s
18047 retransmissions (0,90%)

Using "Pool 1 thread for schedulor, poolsize/2 for others" (plain coap, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 92659ms, 21584 reqs/s
18055 retransmissions (0,90%)
-------------------------------------------

Using ScheduledThreadPoolExecutor (dtls, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 126419ms, 15820 reqs/s
7115 retransmissions (0,36%)


Using "Pool" (dtls, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 119877ms, 16683 reqs/s
5094 retransmissions (0,25%)

Using "Pool with poolsize/2" (dtls, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 112460ms, 17784 reqs/s
6436 retransmissions (0,32%)

Using "Pool 1 thread for schedulor, poolsize/2 for others" (dtls, 1000 clients, 1000 requests)
1000 benchmark clients finished.
2000000 requests sent, 2000000 expected
2000000 requests in 112456ms, 17784 reqs/s
7401 retransmissions (0,37%)
```

**Comment by sbernard31** [comment] 2018-07-06 09:46
> BTW, what's ECL, i do not get your point.

:thinking:  I think @boaks  talks about [ECA](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Eclipse_Contributor_Agreement) ?

**Comment by boaks** [comment] 2018-07-06 10:02
Uups, your right ECA not ECL.

>  "Pool with poolsize/2"

I'm not sure, what this means? "default poolsize (# of cores)  / 2"?

**Comment by sbernard31** [comment] 2018-07-06 12:06
> I'm not sure, what this means? "default poolsize (# of cores) / 2"?

```java
public Pool(int corePoolSize, ThreadFactory threadFactory) {
    super(corePoolSize/2, threadFactory);
    exe  = Executors.newFixedThreadPool(corePoolSize/2, threadFactory);
}
```

**Comment by boaks** [comment] 2018-07-11 14:41
I tried to analyse that a little more:
(All test are done without deduplicator.)

Three different Executors are in use:
- ThreadPoolExecutor, simple job queue, no scheduling, no stripes => very fast
- ScheduledThreadPoolExecutor, priorized job queue, scheduling, no stripes => almost fast
- StripedExecutorService, stripped job queues, no scheduling, stripes => fast

On the client side:
If only one thread is used for the `CoapEndpoint`, a `ScheduledThreadPoolExecutor` must be used to schedule retransmission, but the `StripedExecutorService` is not required (all exchanges are processed by that one thread). On my machine that's about 35000 msg/s for coap and 27000 msg/s for coaps.

If two threads are used for the `CoapEndpoint`, one `ScheduledThreadPoolExecutor` must be used to schedule retransmission, if the other thread is then used to execute the direct jobs, the `StripedExecutorService` is not required (all exchanges are processed by that other thread) and a simple `ThreadPoolExecutor` may be used. On my machine that's also about 35000 msg/s for coap and 27000 msg/s for coaps (very similar to the `ScheduledThreadPoolExecutor`).

If three threads are used for the `CoapEndpoint`, one `ScheduledThreadPoolExecutor` must be used to schedule retransmission, the other threads must then be used for a `StripedExecutorService`. On my machine that's also about 29000 msg/s for coap and 24000 msg/s for coaps.

So in my client side tests, if the `StripedExecutorService` could be omitted, the performance seems not to depend too much on split the scheduled job from the direct jobs. The variance of single runs is larger than that between the executor variants.

The server side is in my opinion intended to run with multiple threads to scale, so the server side must use the `StripedExecutorService`. The difference using the `ScheduledThreadPoolExecutor` or a `Pool`,  which uses also a `ThreadPoolExecutor` for direct execution is on my machine also comparable to the difference of different test runs.

But sure, as more "scheduled jobs" are in the queue, the plain `ScheduledThreadPoolExecutor` get's slower compared to the `Pool`. But using "cf-extplugtest-client/server" benchmark doesn't show that benefit.
 
I started to clean up the executors a little and will provide a PR to reproduce my results. But it may take some time ...

P.S.: I already experimented with a replacement of the "general striped executor" with a "Exchange specialized striper". That eliminates mostly the penalty of the stripped execution.
But it's not stable for now. 
And to be frank, FMPOV, performance is currently not the most important issue.

**Comment by sbernard31** [comment] 2018-07-11 15:47
> And to be frank, FMPOV, performance is currently not the most important issue.

+1

> But using "cf-extplugtest-client/server" benchmark doesn't show that benefit.

That's what I feel too. The benefits seems very slim.

**Comment by boaks** [comment] 2018-07-13 12:35
I published a PR #699 addressing this proposal.

For benchmarks I use:

Server:
cf-extplugtest-server, ExtendedTestServer, with `-d64 -Xmx4g -XX:+UseG1GC -onlyLoopback -noPlugtest`
(4GB heap, if possible)

Client:
cf-extplugtest-client, BenchmarkClient, with `-d64 -Xmx4g -XX:+UseG1GC coap://localhost:5783/benchmark?rlen=40 1000 5000`
(4GB heap, if possible, 1000 clients sending each 5000 GET requests and receives 40 bytes payload, plain coap) 
or `-d64 -Xmx4g -XX:+UseG1GC coaps://localhost:5784/benchmark?rlen=40 1000 5000`
(4GB heap, if possible, 1000 clients sending each 5000 GET requests and receives 40 bytes payload, DTLS encrypted) 

For all benchmarks, please cleanup/delete the "Californium???.properties" before running the test the first time after checkout the PR.

On the client, you may adjust the `PROTOCOL_STAGE_THREAD_COUNT` in "CaliforniumBenchmark.properties". 
1 := 1 ScheduledExecutor only (no striped execution)
2 := 1 ScheduledExecutor, 1 SingelThreadedExecutor, (no striped execution)
3+ := 1 ScheduledExecutor, 1 ThreadPoolExecutor with 2+ threads, StrippedExecutor

@joechen2010 
Maybe your "performance boost" depends on the number of clients and messages. If so, we are very interested to know, what setup you used to get that speedup.

**Comment by boaks** [comment] 2018-08-03 12:42
Any new on this?

**Comment by boaks** [comment] 2018-08-03 13:04
If possible, please test with the new version in the PR #699

**Comment by boaks** [comment] 2018-08-10 08:56
Analysing the results, I recognized, that with the BenchmarkClient / ExtendedTestServer in the first version, the timed task queue didn't get large, because each client uses it's own and the server doesn't schedule to much messages, because mainly ACKs where sent. So the effect of the split the tasks for `ScheduledThreadPoolExecutor` wasn't that large.

With the current version of the PR #699 this changed. Now the client can reuse a shared  `ScheduledThreadPoolExecutor` and though the client uses CON request, it also schedules timed jobs. With that may results are:

```
coaps://localhost:5784/benchmark?rlen=40 2000 1000
```

`SPLIT_THRESHOLD = 0`
> 2000000 requests in 114027 ms, 17539 reqs/s
> 2000000 requests in 120481 ms, 16600 reqs/s
> 2000000 requests in 113449 ms, 17629 reqs/s
> 2000000 requests in 127686 ms, 15663 reqs/s 

`SPLIT_THRESHOLD = 1`
> 2000000 requests in 95170 ms, 21015 reqs/s
> 2000000 requests in 93980 ms, 21281 reqs/s
> 2000000 requests in 93465 ms, 21398 reqs/s

That's a speed-up of 20%!

Maybe someone can confirm it.

**Comment by boaks** [comment] 2018-08-10 10:54
Using

```
coap://localhost:5783/benchmark?rlen=40 2000 1000
```

Results:
`SPLIT_THRESHOLD = 0`
> 2000000 requests in 78299 ms, 25543 reqs/s
> 2000000 requests in 76393 ms, 26180 reqs/s
> 2000000 requests in 75695 ms, 26421 reqs/s

`SPLIT_THRESHOLD = 1`
> 2000000 requests in 71835 ms, 27841 reqs/s
> 2000000 requests in 68893 ms, 29030 reqs/s
> 2000000 requests in 71691 ms, 27897 reqs/s

For plain coap the speed-up seems to be 7%.
DTLS uses the same executer as the `CoapEndpoint `and therefore executes more jobs.
That seems to show a better speed-up.

**Comment by boaks** [comment] 2018-10-03 18:38
@joechen2010 

In the meantime, after being able to reproduce result close to yours, we integrated your idea into californium in the element-connector, `org.eclipse.californium.elements.util.ExecutorsUtil`. 

Thank you very much for this idea!

If you want, please retest (benchmark/profile) our implementation and close this issue.

**Closed** 2018-10-19 20:33 UTC
Labels: could this issue be closed?, retest - validate PR
