### ISSUE TITLE
cannot register exchange : While doing performance test

### ISSUE THREAD

**Issue by phani50** [eclipse/californium#916] opened 2019-03-19 13:00 UTC
12:04:39
2019-03-19T12:04:38.386Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [51340] is not a re-transmission, cannot register exchange
2019-03-19T12:04:38.386Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [51340] is not a re-transmission, cannot register exchange

12:04:39
java.lang.IllegalArgumentException: message with already registered ID [51340] is not a re-transmission, cannot register exchange
java.lang.IllegalArgumentException: message with already registered ID [51340] is not a re-transmission, cannot register exchange 

2.0.0-M5 -- version we are using

**Comment by boaks** [comment] 2019-03-19 13:05
Even if the topic is slightly different, the explanation is the same:

https://github.com/eclipse/californium/issues/883#issuecomment-465739905

Coap is not intended for streaming. The above occurs, if one client runs as-fast-as-possible. But Coap is designed for clients, run on moderate speed, but as-many-clients-as-possible.

**Comment by phani50** [comment] 2019-03-19 13:12
This we are facing in AWS having more instances, and giving continuous requests for perf testing,
Please find below some more logs,


12:59:09
2019-03-19T12:59:08.179Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [1779] is not a re-transmission, cannot register exchange
2019-03-19T12:59:08.179Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [1779] is not a re-transmission, cannot register exchange

12:59:09
java.lang.IllegalArgumentException: message with already registered ID [1779] is not a re-transmission, cannot register exchange
java.lang.IllegalArgumentException: message with already registered ID [1779] is not a re-transmission, cannot register exchange

12:59:09
at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:204)
at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerWithMessageId(InMemoryMessageExchangeStore.java:204)

12:59:09
at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:310)
at org.eclipse.californium.core.network.InMemoryMessageExchangeStore.registerOutboundResponse(InMemoryMessageExchangeStore.java:310)

12:59:09
at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:134)
at org.eclipse.californium.core.network.UdpMatcher.sendResponse(UdpMatcher.java:134)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:656)
at org.eclipse.californium.core.network.CoapEndpoint$OutboxImpl.sendResponse(CoapEndpoint.java:656)

12:59:09
at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:195)
at org.eclipse.californium.core.network.stack.BaseCoapStack$StackBottomAdapter.sendResponse(BaseCoapStack.java:195)

12:59:09
at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:200)
at org.eclipse.californium.core.network.stack.ReliabilityLayer.receiveRequest(ReliabilityLayer.java:200)

12:59:09
at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)
at org.eclipse.californium.core.network.stack.AbstractLayer.receiveRequest(AbstractLayer.java:80)

12:59:09
at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:97)
at org.eclipse.californium.core.network.stack.BaseCoapStack.receiveRequest(BaseCoapStack.java:97)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveRequest(CoapEndpoint.java:837)
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveRequest(CoapEndpoint.java:837)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:766)
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.receiveMessage(CoapEndpoint.java:766)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:729)
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl.access$1000(CoapEndpoint.java:729)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:743)
at org.eclipse.californium.core.network.CoapEndpoint$InboxImpl$1.run(CoapEndpoint.java:743)

12:59:09
at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:981)
at org.eclipse.californium.core.network.CoapEndpoint$5.run(CoapEndpoint.java:981)

12:59:09
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

12:59:09
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)

12:59:09
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

12:59:09
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

12:59:09
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

12:59:09
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

12:59:09
at java.lang.Thread.run(Thread.java:748)
at java.lang.Thread.run(Thread.java:748)

**Comment by mb590721** [comment] 2019-03-19 13:12
How many coap clients are you using to launch your test ?

I already ran into this issue while performing a load test and it was because i was running too many concurrent requests with a single client (IP/Port). 
I solved it by emulating the same number of requests but accross multiple Coap clients/endpoint.

**Comment by boaks** [comment] 2019-03-19 13:19
And, please, if possible, 2.0.0-M5 is from 2017-09-07, we have 2.0.0-M14 from this year.

**Comment by phani50** [comment] 2019-03-19 13:23
yes, we are using same ip/port for 256 requests simultaneously. then we used another port(but IP is same) for next 256 requests in the loop and so on...

**Comment by boaks** [comment] 2019-03-19 13:30
> yes, we are using same ip/port for 256 requests simultaneously.

There is also a NSTART-1 consideration, means: don't fire as-fast-as-you-can!
Wait for the response will automatically throttle the clients. 

> then we used another port(but IP is same) for next 256 requests in the loop and so on...

How many other ports are you using, when do you start to reuse the ports?
And, may be, there is a NAT in between, so could you also please check, which port is seen by your server.

**Comment by boaks** [comment] 2019-03-19 14:11
Just to ensure, that there is no misunderstanding:

- do you want to find out the performance? Then please obey the information above.
- or do you want to report, that even if your client does something not considered, the server should not behave like that? I'm aware of the issues caused by the current deduplicator (see https://github.com/eclipse/californium/issues/905), but It will take time to solve it ...

**Comment by boaks** [comment] 2019-03-19 16:41
I'm still wondering, what your system really receives and sends.

```
2019-03-19T12:59:08.179Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [1779] is not a re-transmission, cannot register exchange
2019-03-19T12:59:08.179Z org.eclipse.californium.core.network.CoapEndpoint SEVERE: Exception in protocol stage thread: message with already registered ID [1779] is not a re-transmission, cannot register exchange
```

This looks like, the MID 1779 is used at least twice (I guess 3 times) in a fast sequence.
May be you provide a wireshark capture from your client and server to see, what your sending and receiving.

By the way: 
do you use CON requests? (I guess, yes)
do you use piggybacked responses (ACK with payload, I guess no).  
do you use separate responses (ACK and CON, I guess yes).
do you use a implementation of your idea "dynamic ACK-CON" of https://github.com/eclipse/californium/issues/197#issuecomment-466042546 (let me guess, **yes**). Switch that of, does your issue disappear?

**Comment by boaks** [comment] 2019-03-28 06:03
@phani50 

Could you solve this issue? If yes, please close it.
Otherwise, did you update to 2.0.0-M14?
Do you use a special implementation for your idea "dynamic ACK-CON"?

**Comment by phani50** [comment] 2019-04-02 04:56
@boaks 

Yes issue resolved, we are following only piggybacked response. (removed customized code). Thanks for the help. i am closing the issue.

**Closed** 2019-04-02 04:57 UTC
Labels: could this issue be closed?, waiting for feedback
