### ISSUE TITLE
Crash inside API CoapObserveRelation.reactiveCancel()

### ISSUE THREAD

**Issue by Rajsmit** [eclipse/californium#187] opened 2016-12-29 06:39 UTC
Hi, 

I found an crash inside API CoapObserveRelation.reactiveCancel(), when we tried to cancel a observer relation. Please check and provide your input.

12-29 15:31:26.781 6871-6871/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.ikea.frekvens, PID: 6871
                                                 java.lang.RuntimeException: Unable to resume activity {com.ikea.frekvens/com.ikea.frekvens.home.activity.WelcomeActivity}: java.lang.IllegalArgumentException: MID must not be a 16 bit unsigned int
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2986)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.lang.IllegalArgumentException: MID must not be a 16 bit unsigned int
                                                     at org.eclipse.californium.core.network.Exchange$KeyMID.<init>(Exchange.java:552)
                                                     at org.eclipse.californium.core.network.Exchange$KeyMID.fromOutboundMessage(Exchange.java:623)
                                                     at org.eclipse.californium.core.network.UdpMatcher$ExchangeObserverImpl.completed(UdpMatcher.java:397)
                                                     at org.eclipse.californium.core.network.Exchange.setComplete(Exchange.java:441)
                                                     at org.eclipse.californium.core.network.stack.ExchangeCleanupLayer$CancelledMessageObserver.onCancel(ExchangeCleanupLayer.java:27)
                                                     at org.eclipse.californium.core.coap.Message.setCanceled(Message.java:556)
                                                     at org.eclipse.californium.core.coap.Request.setCanceled(Request.java:552)
                                                     at org.eclipse.californium.core.coap.Message.cancel(Message.java:624)
                                                     at org.eclipse.californium.core.CoapObserveRelation.reactiveCancel(CoapObserveRelation.java:136)
                                                     at com.ikea.frekvens.network_model.ResourceObserveRelation.cancel(ResourceObserveRelation.java:38)
                                                     at com.ikea.frekvens.shared.manager.LSDataManager.resetObserver(LSDataManager.java:2856)
                                                     at com.ikea.frekvens.shared.manager.LSDataManager.clearData(LSDataManager.java:2816)
                                                     at com.ikea.frekvens.shared.manager.LSDataManager.init(LSDataManager.java:503)
                                                     at com.ikea.frekvens.home.fragment.GatewayDataLoadingFragment.setTimeoutOfProgressDialog(GatewayDataLoadingFragment.java:64)
                                                     at com.ikea.frekvens.home.fragment.GatewayDataLoadingFragment.onResume(GatewayDataLoadingFragment.java:90)
                                                     at android.support.v4.app.Fragment.performResume(Fragment.java:2133)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1156)
                                                     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                     at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                     at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1682)
                                                     at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
                                                     at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:499)
                                                     at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:175)
                                                     at android.app.Activity.performResume(Activity.java:6089)
                                                     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2975)
                                                     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3017) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2392) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
12-29 15:31:30.025 450-466/? E/CwMcuSensor: Sync: sensor hub is on reset

Thanks,
Rajesh Kumar.

**Comment by boaks** [comment] 2017-05-11 15:36
I guess, this is caused by calling the "cancel" before the request got his MID (race condition).
The text itself "MID must not be a 16 bit unsigned int" is wrong. It must be "MID must be a 16 bit unsigned int" (**not** is wrong). 

Did this Exception occur again?

**Comment by sophokles73** [comment] 2017-05-15 11:35
@Rajsmit I tend to agree with @boaks, which version of Cf are you using?

**Comment by Rajsmit** [comment] 2017-05-16 05:35
Hi @boaks/ @sophokles73 , I was using master branch with SHA "a32ab899524675fdf70c3bf65156f74d2c47dc28" on Dec 14.

Currently i am not working in this project so i may not be able support more on this

Thanks.
Rajesh Kumar

**Comment by sophokles73** [comment] 2017-05-17 13:21
Based on our assumption regarding the cause for the problem, I think that this only affects master. `UdpMatcher` on 2.0.x already contains a check preventing unsent requests from being unregistered from the `ExchangeStore` which should prevent this problem from occurring.

I have back-ported that check to master in 925b674da4cbfabd9de3fa1a2e32cca1285e1aad
Hope this fixes the problem. Please re-open if you run into this issue again.

**Comment by boaks** [comment] 2017-05-17 13:42
The Exception is fixed, but I suppose this causes a "leak" in the `UdpMatcher`!  `OutboxImpl.sendRequest` will add the `Exchange` with the MID in the `UdpMatcher` before it stops the sending because it was canceled. But after that, I don't see the cleanup of the Exchange.
Or did I oversee something?

**Comment by sophokles73** [comment] 2017-05-17 13:46
good point, we probably need to add a check to make sure the exchange is not canceled before registering it.

**Comment by boaks** [comment] 2017-05-17 13:49
I would go for call the "cleanup" in OutboxImpl.sendRequest, if canceled and not sent.

**Comment by sophokles73** [comment] 2017-05-17 13:57
sounds good, let me create a PR ...

**Comment by boaks** [comment] 2017-05-17 13:58
:-), I'm on issue #235

**Comment by sophokles73** [comment] 2017-05-17 16:34
should be fixed on master in 5c61b96e23a4c8abab9f7d487fed34b2380a8b1b
on 2.0.x in 0fe9939091047073400cd4524dcceef4cdea844e
on 1.0.x in c78bde605fe9a3d2bad12253608c82ca7269c222

**Closed by sophokles73** 2017-05-17 16:34 UTC
Labels: bug, core
