### ISSUE TITLE
failure in MemoryLeakingHashMapTest

### ISSUE THREAD

**Issue by sheraz045** [eclipse/californium#124] opened 2016-11-06 18:07 UTC
-------------------------------------------------------------------------------
Test set: org.eclipse.californium.core.test.MemoryLeakingHashMapTest
-------------------------------------------------------------------------------
Tests run: 9, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.626 sec <<< FAILURE! - in org.eclipse.californium.core.test.MemoryLeakingHashMapTest
testObserveBlockwise(org.eclipse.californium.core.test.MemoryLeakingHashMapTest)  Time elapsed: 0.655 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at org.eclipse.californium.core.test.MemoryLeakingHashMapTest.assertAllExchangesAreCompleted(MemoryLeakingHashMapTest.java:105)

**Comment by sophokles73** [comment] 2016-11-07 09:12
It would be helpful if you could add some comment explaining what you are trying to achieve and what the problem is you are experiencing.

**Comment by sheraz045** [comment] 2016-11-07 11:08
i am trying to run californium in ubuntu and after running mvn clean install inside the californium folder there is a build failure and inside the report this was one of the failures ,so i need suggestions how to run californium

**Comment by sophokles73** [comment] 2016-11-07 11:33
Which version have you checked out? Master?

Please try to run `mvn clean install` again. On some platforms the build sometimes has problems like this. Sadly, though, we haven't really figured out yet what's causing this yet ...

**Comment by sheraz045** [comment] 2016-11-07 16:08
i use master in ubuntu 15.10

**Comment by boaks** [comment] 2016-11-09 14:55
Could you retest with PR #128.
It was just merged to 2.0.x.

**Closed** 2016-11-15 10:21 UTC
