### ISSUE TITLE
Connection sharing/failover recovery

### ISSUE THREAD

**Issue by Kuczu** [eclipse/californium#1484] opened 2020-12-18 10:12 UTC
Hello,

I uses Scandium as the DTLS server, and it works great. But I need implement a connection sharing between nodes and failover recovery mechanism.
I know that there is shared session cache, but it is uses for abbreviated handshake, unfortunately I have ultra low energy devices which can't (or it is extremely not recommended) do session resumption. So I have to ensure that a connection will be transparency shared between nodes and recovered even after a platform failure.
I saw the new feature for a graceful shutdown, but it doesn't resolve my problems.

I do some research and figured that I can implement my own `ResumptionSupportingConnectionStore` or extend `InMemoryConnectionStore` and use it in the `DTLSServer` (I can do it by extending DTLSServer cos' the constructor which accepts this cache is protected).
As far as I know in the `ResumptionSupportingConnectionStore` I should **have full control of conncetions and sessions** which are established by the DTLSServer so for e.g. I can connect redis to this cache, is that true?

Can you tell me if you have any experience in this kind of problems? Or do you see any problems/corner cases in using own implementation of the `ResumptionSupportingConnectionStore` for this case?

**Comment by boaks** [comment] 2020-12-18 10:36
> I saw the new feature for a graceful shutdown, but it doesn't resolve my problems.

And these problems are?

> unfortunately I have ultra low energy devices which can't (or it is extremely not recommended) do session resumption.

Anyway, they need to make some assumptions about the DTLS session management.

If I put both together:
A device should always be aware, that a timeout may be caused by a lost DTLS session. And so, either use a resumption- or full-handshake to overcome that (one remark: maybe a probe-handshake helps to distinguish between "real timeout" and "no route").
  
It's not important (possible) to eliminate "all handshakes", it's more about to reduce them.
And the graceful shutdown exactly helps to reduce them.

We had some discussions in the past, if you're interested in more background just search our closed issues.
It requires deep DTLS 1.2 knowledge to see, what sharing/failover would really cost.

**Comment by boaks** [comment] 2020-12-18 10:48
By the way:
If you are interested to do experiments about your ideas on yourself,
your welcome to share your questions and results.

**Comment by sbernard31** [comment] 2020-12-18 10:57
Our current experience about using redis for `SessionCache` seems to show a CPU consumption increase. (which could maybe be reduce using some local in memory cache). I said that just to let you know that IF creating a shared/persistent redis cache for connection is possible (I don't know with current code base) THEN it could be CPU costly at server side.

**Comment by Kuczu** [comment] 2020-12-18 11:08
> And these problems are?
I have to ensure failover recovery. For e.g. when the pod with dlts server unexpectedly goes down - without graceful shutdown I lose my connections' information.

> We had some discussions in the past, if you're interested in more background just search our closed issues.
I have read closed issues which seems to be connected with my issue but I didn't find answers for my case and I have not noticed a similar idea as mine.

My main question is the `ResumptionSupportingConnectionStore` is the only store with connections/sessions information? If I implements my own `ResumptionSupportingConnectionStore` and pass it to the `DTLSServer` instance should I have full control of the established connections? If yes, so why it can be a problem to use additional cache (e.g. redis) with some local caching tweaks?
@sbernard31 I know that redis alone will decrease the performance but in the future I can do some tweaks and play with local cache

**Comment by sbernard31** [comment] 2020-12-18 11:35
> I know that redis alone will decrease the performance but in the future I can do some tweaks and play with local cache

My concern are : Local cache for connection could be more complicated as each message needs connection update (@boaks already explain me that but I can find the discussion :confused:) and access to connection is really more frequent than access to session.

**Comment by boaks** [comment] 2020-12-18 12:07
> I have read closed issues which seems to be connected with my issue but I didn't find answers for my case and I have not noticed a similar idea as mine.

Your idea, to mirror the association/connection state, was discussed several times. Sure, a lot to read and it's not distilled out of multiple comments.

The dtls-association/connection-state, which would be required to be shared, has several parts.

[generally the "association (connection) state - keys, anti-reply window" could be transferred to other nodes](https://github.com/eclipse/californium/issues/1045#issuecomment-524174388)

1. a session with crypto-parameter, e.g. cipher suite, principal, and the master secret.
1. the association read/write key materials, connection ids, if used
1. an inet-socket-address
1. the sending record-sequence-number, and the receive window of the received record-sequence-number.

These data is changing in the above order, the record-sequence-number are usually adapted by all successful record exchanges. The "graceful-shutdown" demonstrates, how to save and load that.

If a "cluster" is successful or not, depends in my opinion on 
1. the number of nodes, 
2. the performance exchanging such state, 
3. the definition of "weak-consistence", 
4. and the frequency on how the information has to be exchanged.

So, that's a wide area, to try out a "weak-consistence" model and an actual implemented "inter-node-information-exchange". E.g. you may just update the "exchanged" record-sequence-number on every 32 records. On a failover, just add that interval (32) to the last read value. If this is working and which performance results out of that, that is the "developer-tester-time-intensive" task.
(e.g. the basics for the "build-in support for cid-load-balancing" was about 2 weeks, all test (among other stuff) 3 months. In the graceful-restart I spend now about 1 week, I will publish the newest wip in the afternoon. To complete that, requires 1. to redesign the Connection/DTLSSession/DtlsConnectionState and then to improve the persisted features, e.g. detect "hello_client" duplicates timeout. So still a lot of work.)

So again:
Your idea will require many experiments, or it will slow down the record processing very hard.
Your requirement, doing "no handshakes", is in my opinion "over done", it's about doing "less handshakes". And using the graceful-restart is a good starting point for that.

I'm not sure, how many vm/node crashes you have been affected. In my experience, these are very rare, once or twice a year per system. Californium crashes should be even rarer (OK, that may be wrong :-) ). As I explained above, to successfully overcome that, will require a lot of work and time. At least for now, FMPOV, that doesn't payoff. But sure, If you want to invest your time, then your experience, questions and results are very welcome.

**Comment by Kuczu** [comment] 2020-12-21 23:53
@boaks thank you for your comprehensive answer!
My general idea is that I have couple of nodes with DTLS server, every node has a local cache (L1) (something like `InMemoryConnectionStore`) and additional shared cache L2 (e.g. redis). Every interaction with connection will change cache L1 (as it is now), and every given period (e.g. 10-15 sec) the connections state would be pushed to the cache L2.
There is assumption that a connection will always be handled by the same node (if it still works), if node fails then a new node will be selected. It will be ensured at the load balancer level - for e.g. session affinity or in the future by `CID`.
So when request comes to the cluster it goes to the node, node checks if know this connection in cache L1, if is known then will handle it as usual, if not then checks if connection is in the cache L2, if is known then copy record to the L1 and handle it as usual. When request is a handshake it will establish a new connection.

I know that there will be drawbacks:
* the first is server resources - pushing/syncing data with redis will cost, but afaik for my case it is ok - ofc I must test how much it will really take.
* the second is data consistency, there is a window in within the data can be out of sync, 10-20sec - when a node goes down and will not push the fresh data into cache L2. But I think it should not be a big deal, failures don't happen often :)
Afaik even if L2 will contains, out of sync, 20sec old data it should not be a big deal - in the worst case there will be possible to perform a (one?) replay attack (for this window) or just connection will be dropped by DTLSServer?

**Comment by boaks** [comment] 2020-12-22 08:14
> ofc I must test how much it will really take.

> failures don't happen often :)

That's the point. So, as long as you want to spend your time, your welcome.

If you want to start, just modify that `InMemoryConnectionStore` according your ideas.
The newly added "serialize/deserialize" for Connections may be used (with care, it's WIP,  and the format will change). If the "record sequence  number/window" updates should be handled more efficiently, we may add also a callback for that.
There is a discussion about the session cache and to do a redesign ahead (see at the end of the discussion in issue #1345). My personal preference is always: 1. test, if the approach makes sense at all, 2. if it makes sense, then apply a well defined design. But it's also possible to prepare a "wip" branch, if more modifications are required (redesign) and the work may take longer.

**Comment by boaks** [comment] 2020-12-23 12:08
@Kuczu 

Just if you're interested in first experience:
PR #1486 gets more and more "usable". Especially, if you find yourself having too less time, it may be also your benefit to provide test feedback to the graceful shutdown and use that for the next months.

**Comment by boaks** [comment] 2021-01-25 06:44
@Kuczu 

If you want to work on this issue, we can leave it open. If not, could it be closed?

**Closed** 2021-01-26 19:35 UTC
Labels: could this be closed?

**Comment by boaks** [comment] 2021-02-17 19:33
The blue/green update with DTLS graceful restart is available for testing!

Checkout PR #1547 !
