### ISSUE TITLE
Cannot use interface on IPv6 in URI on secure connection: not a valid host name

### ISSUE THREAD

**Issue by paxter** [eclipse/californium#1063] opened 2019-09-04 18:56 UTC
I'm using 2.0.0-M16.

This works fine:
```
CoapClient client = new CoapClient("coap://[fe80::949a:f3ff:feb7:2b0%interface0]:5683/update";
client.post(payload, MEDIATYPE);
```

But with DTLSConnector it fails:

```
CoapClient client = new CoapClient("coaps://[fe80::949a:f3ff:feb7:2b0%interface0]:5684/update";
DtlsConnectorConfig.Builder builder = new DtlsConnectorConfig.Builder();
dtlsConnector = new DTLSConnector(builder.build());
CoapEndpoint.Builder builder = new CoapEndpoint.Builder();
builder.setConnector(dtlsConnector);
builder.setNetworkConfig(NetworkConfig.getStandard());
client.setEndpoint(builder.build());
client.post(payload, MEDIATYPE);
```

Stacktrace:

```
java.io.IOException: java.lang.IllegalArgumentException: not a valid host name
	at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1109)
	at org.eclipse.californium.core.CoapClient.synchronous(CoapClient.java:1081)
	at org.eclipse.californium.core.CoapClient.post(CoapClient.java:568)
	at updateserver.CoapClient.sendSecureRequest(CoapClient.java:87)
	at updateserver.CoapClient.sendSecurePostRequest(CoapClient.java:111)
	at updateserver.Tests.main(Tests.java:62)
Caused by: java.lang.IllegalArgumentException: not a valid host name
	at org.eclipse.californium.scandium.util.ServerName.fromHostName(ServerName.java:83)
	at org.eclipse.californium.scandium.util.ServerName.from(ServerName.java:60)
	at org.eclipse.californium.scandium.dtls.DTLSSession.setVirtualHost(DTLSSession.java:368)
	at org.eclipse.californium.scandium.DTLSConnector.sendMessage(DTLSConnector.java:1974)
	at org.eclipse.californium.scandium.DTLSConnector.access$1400(DTLSConnector.java:214)
	at org.eclipse.californium.scandium.DTLSConnector$13.run(DTLSConnector.java:1907)
	at org.eclipse.californium.elements.util.SerialExecutor$1.run(SerialExecutor.java:277)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I think there is an issue and both should work.

**Comment by boaks** [comment] 2019-09-04 19:50
I can't reproduce, that there is a difference between coap and coaps. 
And I can't see, that the implementation of hostname resolving depends on that.

I can reproduce, that using a wrong "scope" doesn't work for both.  
If the scope is available it works.
Did you test the stuff on different hosts? One with such a "interface0" and the other without?

**Comment by paxter** [comment] 2019-09-04 19:52
No, it's exactly the same machine. I only switched from coap to coaps.

**Comment by boaks** [comment] 2019-09-04 20:01
I tested it, and yes, the Request.IP_PATTERN doesn't consider the scope. I'll fix it.

**Comment by paxter** [comment] 2019-09-04 20:03
Awesome. Thanks a lot for your fast reply and help. :)

**Comment by boaks** [comment] 2019-09-04 20:12
Checkout master, hope it works :-), Then it will be part of 2.0.0-M17

**Comment by paxter** [comment] 2019-09-04 20:24
Thanks a lot. :) Because I'm not very familar with java/maven, I've first to find out how I can replace the code.

**Comment by boaks** [comment] 2019-09-04 20:28
Then wait for tomorrow. We release 2.0.0-M17 with that fix and you may retest it then with that milestone.

**Comment by paxter** [comment] 2019-09-04 21:27
Yep, it works. :) Thanks again.

**Closed** 2019-09-04 21:27 UTC
Labels: bug, retest - validate PR

**Comment by boaks** [comment] 2019-09-05 05:01
Thanks for the feedback.
