### ISSUE TITLE
DTLS Connection saving to store

### ISSUE THREAD

**Issue by Stanislaw-Jakiel** [eclipse/californium#89] opened 2016-09-15 14:08 UTC
Starting new handshake (upon receiving _ClientHello_) is done in
`org.eclipse.californium.scandium.DTLSConnector#startNewHandshake`
The very fist step is saving the connection to _store_
Then deep under the invocation of:
`handshaker.processMessage(record)`
the method `org.eclipse.californium.scandium.dtls.ServerHandshaker#receivedClientHello` is called
which in turn "updates" just saved _connection_ entity (via `handshakeStarted()`).
But this "update" doesn't have any effect on persisted entity, so when the DTLS client side sends next message the connection fetched from the _store_ lacks any information about "updated" objects (e.g. _DTLSSession_ or _Handshaker_), thus whole handshake fails
It works with `org.eclipse.californium.scandium.dtls.InMemoryConnectionStore` as you refer to the same object.
Q: Is this by design? So that storage always have some kind of in-memory LRU cache? Otherwise I think this is bug

**Comment by sophokles73** [comment] 2016-09-21 09:30
You are right in that the way that `ConnectionStore` is integrated into the handshake on current master lacks the necessary callbacks to keep a connection in sync with its persisted state (when not keeping connections in memory only). I have been re-thinking the way connection state can be shared among multiple nodes some months ago and have created the `session_cache` branch for that purpose.

I now think that it doesn't make much sense to persist a connection and try to keep its full state in sync with its in-memory representation simply because the persistent state would need to be updated on every message received or sent (because of the record counters). However, I think it makes sense to provide means to persist an established session's crypto parameters, thus enabling other nodes to perform an abbreviated handshake with a client to resume a session the client has originally established with a node that has failed.

For that purpose I have introduced a `SessionCache` interface which is what client code could provide its specific implementation for when instantiating the `DTLSConnector`. We no longer support specific implementations of `ConnectionStore` but instead always use an `InMemoryConnectionStore` which can optionally be configured to use a specific `SessionCache` implementation which could e.g. persist session state to Redis or a DB. To make that easier I have also provided `org.eclipse.californium.scandium.auth.PrincipalSerializer` for serializing the authenticated client principal to/from a byte array.

Because the `InMemoryConnectionStore` implements `SessionListener`, it will be notified about established sessions and puts them into the `SessionCache` (if configured).

Does this make sense to you? Would a custom `SessionCache` implementation work for you?

**Comment by sophokles73** [comment] 2016-09-22 14:07
See #96

**Comment by sophokles73** [comment] 2016-09-29 07:02
@Stanislaw-Jakiel,

I have merged PR #96 to the 2.0.x branch. Would you care to take a look if this helps with your problem?

**Comment by sophokles73** [comment] 2016-09-30 07:26
This is also merged to master now.

@Stanislaw-Jakiel: please create another issue if this does not fix your problem.

**Closed by sophokles73** 2016-09-30 07:26 UTC
Labels: question, scandium

**Comment by Stanislaw-Jakiel** [comment] 2016-10-06 15:01
Thank you for answer and please excuse my absence.
Having read your response and the: [#96](https://github.com/eclipse/californium/pull/96)
It does seem reasonable **not** to store all dtls session related parameters as this will require **a lot** of updates (even with some kind of batching it will still be too much).
By choosing this solution we accept loosing packets (e.g. incoming encrypted CoAP NON messages will be dropped if the server node was restarted or lost the dtls session)

However one question (from @balsmn) remains: when does the client decide whether to perform abbreviated or full handshake? Should it be the responsibility of upper layers to mark the client dtls session as _requiring resumption?_ (i.e. when CON message failed to deliver? or even higher: when update request failed?)
Additionaly: (please correct me if I'm wrong) DTLS client-server relation is kind of "floating" - server also  can send _ClientHello_, right?
Imagine this situation (LWM2M case): 
1. Client registers at LWM2M server (with underlying DTLS)
2. Server stores the DTLS session parameters
3. Server restarts
4. Server wants to send some requests to client (assume binding mode = U, not using Queue mode)
5. If DTLS client-server relation is indeed "floating" the server must send _ClientHello_ first, can it use the abbreviated Handshake?
If so maybe the: `org.eclipse.californium.scandium.DTLSConnector#sendMessage(org.eclipse.californium.elements.RawData)` should use find method to retrieve connection (in order to search for "previous" session)?

**Comment by sbernard31** [comment] 2016-10-07 10:02
My 2 cts.

>By choosing this solution we accept loosing packets (e.g. incoming encrypted CoAP NON messages will be dropped if the server node was restarted or lost the dtls session)

DTLS or not if you use NON message, you accept to lost packet.

>Additionaly: (please correct me if I'm wrong) DTLS client-server relation is kind of "floating" - server also can send ClientHello, right?

Its not so clear for me, but I think so.

>However one question (from @balsmn) remains: when does the client decide whether to perform abbreviated or full handshake? Should it be the responsibility of upper layers to mark the client dtls session as requiring resumption? 

Mainly yes.

>If DTLS client-server relation is indeed "floating" the server must send ClientHello first, can it use the abbreviated Handshake?

I suppose it could. If the device does not support this and is correctly implemented we should automatically go for a full handshake. This is a possible optimization but I'm not sure this will often happened. Do you have real use case with U binding mode (I'm mean device with fixed IP address)

**Comment by kiemlicz** [comment] 2016-10-10 09:53
> DTLS or not if you use NON message, you accept to lost packet.

Yes, that is true. 
Although now It's guaranteed loss, introduced by design (when multi-node deployment of DTLS is used + packet reaches node without DTLS state)

>  This is a possible optimization but I'm not sure this will often happened. Do you have real use case with U binding mode (I'm mean device with fixed IP address)

I'll use LwM2M:
1. Client registers in LwM2M server (the device initiates whole communication: dtls + lwm2m), uses lifetime parameter equal to 86400 seconds, or even more (namely it will come back at least one day later) and uses U binding mode.
2. During that lifetime server restarts
3. Server wishes to issue some requests via _management interface_. As there is no DTLS active connection it will try to establish the new one (this makes me think that dtls client-server relation is "floating"). If you have millions of devices imo it would be better to use abbreviated handshake to reduce the handshake complexity (after all parameters are already negotiated).

**Comment by sophokles73** [comment] 2016-10-10 14:02
Is there anything else we need to clarify regarding this issue or can we close it?

@kiemlicz: feel free to create a PR for also looking up existing session state from `SessionCache` from client side.
