### ISSUE TITLE
Big file download request with block2

### ISSUE THREAD

**Issue by bujingyun8** [eclipse/californium#809] opened 2018-11-27 09:47 UTC
my device want to download a file,so send request with block2,the size of my file is about 200KB.
so I add a resource and override the handleGET method like  behind:

		try {
			File file = new File("C:\\Java\\a.bin");
			if (file.isFile()) {
				FileInputStream fis = null;
				fis = new FileInputStream(file);
				byte[] buf = new byte[(int) file.length()];
				ByteArrayOutputStream bos = new ByteArrayOutputStream(1024);
				byte[] b = new byte[1024];
				int n;
				while ((n = fis.read(b)) != -1) {
					bos.write(b, 0, n);
				}
				fis.close();
				bos.close();
				byte[] payload = bos.toByteArray();
				exchange.respond(ResponseCode.CONTENT, payload);
			} else {
				exchange.respond(ResponseCode.NOT_FOUND);
			}
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}

BUT the server sometimes response timeout.I want to know if the code has some troubles?or any other?

the  version is M5

**Comment by boaks** [comment] 2018-11-27 09:54
https://github.com/eclipse/californium/issues/792#issuecomment-439445594

> The basic change you need, is to adjust the MAX_RESOURCE_BODY_SIZE to your expected file size on both sides, server and client. You may just edit the "Californium.properties".

**Comment by boaks** [comment] 2018-11-27 11:35
In Bytes. Try it, and report your result. If it doesn't work, we will see ...
We have M12 so maybe, you can also try to update.

**Comment by boaks** [comment] 2018-11-27 11:56
I tested it right now for M5.
Delete the "Californium.properties", start the file server and get client once and stop them.
Edit the "Californium.properties" (file server and get client) setting the `MAX_RESOURCE_BODY_SIZE` to a proper value for your use-case.
"On my machine, it works :-)"

**Comment by bujingyun8** [comment] 2018-11-28 06:12
It works OK,but the problem is still not solved.somethings the client will recieve timeout.
I want to know whether should  I split the file in the handleGET method.or coap server do it?

I have seen the log,if I response the all bytes of the file,the server will crop response body.
I'm not sure if the performance is good or not.
Should I cache the file,and get the block (szx=2/64, m=false, num=920),crop the file from cache.
and then response the 64 bytes only?



2018-11-28 13:53:12.946 DEBUG 6255 --- [CoapServer#1] o.e.c.core.network.stack.BlockwiseLayer  : peer wants to retrieve individual block2 (szx=2/64, m=false, num=920), delivering request to application layer
2018-11-28 13:53:12.947 DEBUG 6255 --- [CoapServer#1] o.e.c.c.n.stack.Block2BlockwiseStatus    : cropping response body [size=82275] to block (szx=2/64, m=false, num=920)
2018-11-28 13:53:12.947 DEBUG 6255 --- [CoapServer#1] o.e.c.c.network.stack.ReliabilityLayer   : Send response, failed transmissions: 0

**Comment by boaks** [comment] 2018-11-28 08:58
> It works OK,but the problem is still not solved.somethings the client will recieve timeout.

I'm not sure, which client you exactly use. And you may provide some information about your communication environment.

`szx=2/64, m=false, num=920`

You use a `PREFERRED_BLOCK_SIZE` of 64. Is your device connected with a very small path MTU?
(Means: you have some link, which is more efficient to transfer multiple blocks of 100 bytes that one block of 1000 byte, e.g bluetooth LE). If you not limited, may be you increase that blocksize. That's done by adjust the `PREFERRED_BLOCK_SIZE` in the Californium.properties, the smallest one of the server and client will be used, so maybe you need to adjust both.

I only see the log for block 910, do you have also the log message for block 905 (than we can estimate your request/response delay) or block 1 (to estimate your full download time).
If the full-download time is about 240s, and you use the `CoapClient`, use the `setTimeout` and adjust a estimated request/response  time + some extra time.

And just not to forget: 
Blockwise in the real world may require a lot more. You may be faced of single block timeouts and want to resume the download of the rest blocks later. All that will not be done in the "transparent" mode of californium. For hat you must implement your own situation optimized solution.

**Comment by bujingyun8** [comment] 2018-11-28 12:41
My device using NB network,the PREFERRED_BLOCK_SIZE is limited less then 512B.
the size of per file is about 100K
Really,my trouble is  single block timeouts,my device will retry to download the same block.
But now I dont know why single block request timeout.
if it can't work well in the "transparent" mode,is there some advice？

**Comment by boaks** [comment] 2018-11-28 13:32
Required "less 512b" and used "64b" is a large difference!
If you use 256b, the download should get faster.

> Really,my trouble is single block timeouts,my device will retry to download the same block.

If I assume 1s single block request/reponse time per block in your NB, and I see 900 blocks, then this would take 900s! So the timeout for the CoapClient full response must be adjusted.

So, please, first at all, determine your single block request/response timeout!
Then calculate the timeout for the full download.
If possible, you may record a capture of a broken download (server side using wireshark), that would also contain very useful information. Please ensure, that you use a dummy download file for the capture. And filter the captured pakets with "coap" and export only these records. Such a capture helps a lot! 

In the past it was too common, that the "overall timeout 240s" expires and "timesout" even a proper "single block request/response".

In the "real world" there may be some temporary network issues, which may "interrupt" such a download. But to start "in laboratory", the demo download should work.

**Comment by boaks** [comment] 2018-11-28 20:21
> if it can't work well in the "transparent" mode,is there some advice？

I didn't say "it can't", but in my experience, in the real world some blockwise download will fail caused by temporary issues. Then it's up to the application, if it continues next time or restart the download.

To disable the blockwise for the client, configure the MAX_RESOURCE_BODY_SIZE to 0.

with that your client will just get the first block and is responsible the get the next blocks using the block2 option. So the application can decide, when to stop or pause a transmission.

**Comment by boaks** [comment] 2018-12-05 13:55
So, doest it work for you? If so, could you please close this issue?

**Closed** 2018-12-14 09:03 UTC
Labels: could this issue be closed?

**Comment by boaks** [comment] 2018-12-14 09:05
Don't hesitate to add a new comment or open a new issue, when you have new information for us.
