### ISSUE TITLE
Async Push:  Parsing message without a session

### ISSUE THREAD

**Issue by qux42** [eclipse/californium#23] opened 2016-03-18 10:03 UTC
Hello,

I found a strange behavior, trying to make async pushes. 
The Logger says "Parsing message without a session".
If I make a sync push before the async pushes, everything works fine...

[Here](https://github.com/qux42/californium-push-bug) is a minimal [example](https://github.com/qux42/californium-push-bug) of my problem.

**Comment by sophokles73** [comment] 2016-04-12 12:26
Scandium currently requires client code to synchronously establish the initial DTLS session with the server before sending arbitrary (sync or async) requests over the established session.
If you do not do so Scandium starts mulitple concurrent handshakes with the server (one for each async request) until one of the handshakes has finished.
We need to properly document this and maybe also prevent client code from submitting more requests until the session is established.

**Comment by sophokles73** [comment] 2016-04-12 14:15
Also see [here](https://github.com/eclipse/californium.scandium/issues/29) for a description of what happens under the hood.

**NB** please do not comment on the referenced issue in *californium.scandium* because we have merged Scandium into the Californium repo.

**Comment by boaks** [comment] 2017-09-28 09:08
Is this still an issue? If so, I think one solution to fix it, would be adding and additional newDeferredMessageSender to the "ongoing handshake" instead of starting a new one.
Any opinions on this?

**Comment by sbernard31** [comment] 2017-11-24 15:33
@boacks I suppose this should works. (Even if I suspect some possible race condition)

**Comment by boaks** [comment] 2017-11-29 13:29
It seems to be no longer a issue of interest, so I would rather close than fixing it :-).

Even if this issue was not caused by coap retries during a ongoing handshake, such retries are from my experience mainly the cause for such problems. But in the meantime, such retries are not longer the case.

**Comment by boaks** [comment] 2018-03-12 11:54
Testing I found, that if "notifications" trigger a handshake (e.g Automatic session resumption is used), fast following notifications may be dropped. 

So FMPOV, this issue should be fixed :-)

**Closed** 2018-10-08 19:47 UTC
Labels: enhancement, scandium, waiting for feedback
