### ISSUE TITLE
InMemoryMessageIdProvider default size

### ISSUE THREAD

**Issue by sbernard31** [eclipse/californium#221] opened 2017-02-24 16:31 UTC
I made some tests with the 2.0.0-M2 version. I launched several hundred of client in the same VM which try to connect to a server in another VM.

I recently try with master and the memory consumption has significantly increased.

After some investigation, the problem is about `InMemoryMessageIdProvider` initialization :
The `InMemoryMessageIdProvider` contains an LRU Cache with a size initialize to `MAX_ACTIVE_PEERS` (500 000 by default).

Practically for a client which will connect to only 1 or 2 server, we go from 4MB to 8MB of heap space.
User can change the `MAX_ACTIVE_PEERS` to a more reasonable value, but I don't think this is a good idea to [initialize the cache size to the max size](https://github.com/eclipse/californium/blob/master/element-connector/src/main/java/org/eclipse/californium/elements/util/LeastRecentlyUsedCache.java#L93).

**Comment by sophokles73** [comment] 2017-02-27 08:33
I agree, this doesn't seem to make much sense for a client. So, what do you think would be a reasonable default value? I am also a little concerned about scaling up the map (when used on the server side) during runtime? Do you have any experience with this? Is the time it takes to scale up the capacity from e.g. 1000 - 100.000 negligible?

**Comment by sbernard31** [comment] 2017-02-27 14:40
I just launched this kind of benchmark :

```java
   @Benchmark
    public void without_initialization(ConnectionPool cp) {
        HashMap<Integer, Connection> map = new HashMap<Integer, Connection>();

        for (int i = 0; i < 500000; i++) {
            map.put(i, cp.connections[i]);
        }
    }

    @Benchmark
    public void with_initialization(ConnectionPool cp) {
        // value used in the LeastRecentlyUsedCache class
        HashMap<Integer, Connection> map = new HashMap<Integer, Connection>(500000 + 1, 1.0f); 

        for (int i = 0; i < 500000; i++) {
            map.put(i, cp.connections[i]);
        }
    }
```
Here the result : 
```
# JMH 1.17.4 (released 40 days ago)
# VM version: JDK 1.8.0_121, VM 25.121-b13
# VM invoker: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
# VM options: <none>
# Warmup: 20 iterations, 1 s each
# Measurement: 20 iterations, 1 s each
# Timeout: 10 min per iteration
# Threads: 1 thread, will synchronize iterations
# Benchmark mode: Average time, time/op

Benchmark                                 Mode  Cnt  Score    Error  Units
LeastRecentlyUsed.with_initialization     avgt   20  0,013 ±  0,001   s/op
LeastRecentlyUsed.without_initialization  avgt   20  0,027 ±  0,001   s/op
```
We can see that the order of magnitude is around 15 to 30 ms to fill the entire map on my workstation. I think this is clearly not an issue.

**Comment by sophokles73** [comment] 2017-02-27 15:16
Thanks for doing the hard work, man :-) So I guess it would be ok to initialize the cache with an initial capacity of e.g. 1000 and then let it scale up dynamically.

**Comment by sophokles73** [comment] 2017-02-27 15:17
fixed on master in e788d077f73e4794522910719981351604ac52e3
fixed on 2.0.x in 537432a37be43f4762d95edc1e93b5528939e727

**Closed by sophokles73** 2017-02-27 15:17 UTC

**Comment by sbernard31** [comment] 2017-02-27 15:41
Personally, I would prefer to not initialize it by default (I mean let the hashMap implementation default value which is 16).

**Comment by sophokles73** [comment] 2017-02-27 15:47
Are you talking just about `InMemoryMessageIdProvider` or `LeastRecentlyUsedCache` in general?

**Comment by sbernard31** [comment] 2017-02-27 15:50
`LeastRecentlyUsedCache` in general.

**Comment by sophokles73** [comment] 2017-02-27 16:04
Ok, if it makes you sleep better, I have no problem with setting it to 16 ;-)

**Comment by sbernard31** [comment] 2017-02-27 16:15
I meant using `new HashMap()` instead of setting it to 16 :p

**Comment by sbernard31** [comment] 2017-02-27 16:18
Now it's you who will make nightmares about me ^^

**Comment by sophokles73** [comment] 2017-02-27 16:22
I am not sure whether you are serious or just kidding. In any case, be my guest to re-open the issue and change it to your liking :-) FMPOV the issue is closed.
