### ISSUE TITLE
Why is ServerMessageDeliverer final?

### ISSUE THREAD

**Issue by LudwigSeitz** [eclipse/californium#318] opened 2017-06-01 06:51 UTC
Hello,

I just noticed that the ServerMessageDeliverer (SMD) class was changed to final in some (not so recent) update. Is there any particular reason for doing so?

I am currently using an older version where I subclass SMD to implement access control on incoming messages (on recommendation by Matthias btw.), having to re-implement the SMD instead of subclassing it is quite inconvenient.

**Comment by boaks** [comment] 2017-06-01 10:39
Hm, I think delegation should be also possible in a few lines.

But I hope @sophokles73 will give an answer, why "final" was introduced a year ago.

**Comment by boaks** [comment] 2017-06-13 11:16
Hm, may be too long ago :-).

Does "delegation" work for you?

**Comment by LudwigSeitz** [comment] 2017-06-13 12:06
Never used delegation, do you mean Java8 lambda expressions, or pre-Java8 workarounds?

**Comment by boaks** [comment] 2017-06-13 12:50
Just a own implementation of `MessageDeliverer`, which hold it's own instance of `ServerMessageDeliverer` (delegate) and the own implementation does the additional stuff and call the `ServerMessageDeliverer` instance to do the californium internal stuff.

**Comment by sophokles73** [comment] 2017-10-26 06:15
@LudwigSeitz can we close this issue?

**Comment by LudwigSeitz** [comment] 2017-11-01 07:08
Well since no one seems to be able to answer the question, I would suggest to "unfinal" SMD, unless there is a good reason to have it final.

**Comment by sophokles73** [comment] 2017-11-01 08:14
well, the class isn't designed for extension (yet). The proper functioning of the server depends on some of the functionality of the `ServerMessageDeliverer` actually being in place and being executed for an incoming message. Making it `final` was supposed to indicate that this is not a class that can be easily extended without some expert knowledge. However, maybe we can change it to support extension by making (most of) its methods finals and provide reasonable hooks to plug in, i.e. provide empty implementations of methods that are invoked at certain points of the processing chain so that subclasses can simply override these hook methods in order to *inject* their custom behavior. WDYT? Would that work for you?

**Comment by LudwigSeitz** [comment] 2017-11-01 08:27
Thanks for the explanation. I'm extending  ServerMessageDeliverer to do some additional processing on all incoming requests (in my case access control). I asked Matthias Kovatsch for the best place to do that and he suggested  ServerMessageDeliverer. I would be happy with any solution that allows me to :

1.   Intercept certain types of messages (incoming requests in my case)
2.  Process them preferably with the Exchange available
3.  Be able to prevent further processing at the resource and deliver a reply directly

**Comment by sophokles73** [comment] 2017-11-02 08:16
ad 1) The deliverer deals with incoming requests and responses. We could add hooks that subclasses could implement to either *preprocess* an incoming request/response and then let the `ServerMessageDeliverer` do its standard processing or to *preempt* processing altogether, i.e. the subclass alone would then be responsible for processing (and e.g. produce a response) without the `ServerMessageDelieverer` interfering anymore.
ad 2) We would then pass the current exchange as a parameter to the hook methods.
ad 3) see 1

Does this make sense to you?

**Comment by LudwigSeitz** [comment] 2017-11-02 09:48
Yes it does. Thanks for the quick feedback.

**Comment by sophokles73** [comment] 2017-11-02 09:55
BTW Which branch are you using?

**Comment by LudwigSeitz** [comment] 2017-11-02 10:02
Currently 1.0.5 but I'd like to update to a later one (which is where I encountered the problem of SMD suddenly becoming final).

**Comment by sophokles73** [comment] 2017-11-02 10:19
Ok, so I will try to do this on all branches then. I do not know if I will find the time today but I guess it should be done by the beginning of next week ...

**Comment by sophokles73** [comment] 2017-11-03 17:07
Hi @LudwigSeitz 
can you take a look at #466 and check if this would work for you?

**Comment by LudwigSeitz** [comment] 2017-11-06 08:24
Looks good. Thanks!

**Comment by sophokles73** [comment] 2017-11-06 14:43
fixed on 2.0.x in c15c4ba9318794e001ecfed4260faaa633ba4641
fixed on master in 4978aafabec9f134368b8aecc034be95f10110d1

**Comment by sophokles73** [comment] 2017-11-22 11:07
@LudwigSeitz can you close this issue if it fixes the problem for you?

**Comment by LudwigSeitz** [comment] 2017-11-22 12:10
It seems to be closed already (and I'm fine with that)

**Comment by sophokles73** [comment] 2017-11-22 12:27
oh, yes, my bad. Sorry to bother you ...

**Comment by boaks** [comment] 2018-03-28 07:14
On behalf of Clement Pellerin

I would like to make a case to reopen issue #318 because I think we need to remove the final keyword on ServerMessageDeliverer.findResource()

This is the best place to implement wild cards in URI searches like the javadoc suggests:
	 * Searches in the resource tree for the specified path. A parent resource
	 * may accept requests to subresources, e.g., to allow addresses with
	 * wildcards like <code>coap://example.com:5683/devices/*</code>

Unfortunately, the final keyword on findResource() makes this impossible without reimplementing all of deliverRequest(). I don't see how the new preDeliverRequest() helps since we still have to reimplement all of deliverRequest(), so might as well reimplement deliverRequest() directly.

I would argue it is more dangerous to force people to reimplement deliverRequest() and hide any future changes you might make, compared to allowing findResource() overrides. By trying to hide the internals of ServerMessageDeliverer, you are exposing them a lot more.

The only thing missing after removing the final keywords is to add a getRoot() accessor because it is needed to implement our own findResource().

I'm asking for findResource(), but I would prefer if none of the ServerMessageDeliverer methods were final.

**Comment by sbernard31** [comment] 2018-04-09 16:15
> I'm asking for findResource(), but I would prefer if none of the ServerMessageDeliverer methods were final.

:+1:

**Comment by boaks** [comment] 2018-04-12 05:12
> This is the best place to implement wild cards in URI searches like the javadoc suggests:

Take a look at cf-simplefile-server, SimpleFileServer, FileResource:
```
		/*
		 * Override the default behavior so that requests to sub resources
		 * (typically /{path}/{file-name}) are handled by /file resource.
		 */
		@Override
		public Resource getChild(String name) {
			return this;
		}
```

That's the intended way to implement resources, which applies to a "wildcard URI". It catches up all requests to the resource and "all virtual child resources".
  
The other usecase, using a wildcard in the request's URI, is intended to use the discover with search query options. This would result in the matching links.

(The only nasty seems to be, that using wildcard resources doesn't support discover :-) ).

About the general removing of the `final`:
That's more a question to the API design and grants. Using `final` indicates, that it is not intended to overwrite this method, because it seems to probable, that this crocs too much.
So, what was your implementation idea? Can you post your `findResource()`? Does it support the wildcard resource? Does it support discover?

**Comment by sbernard31** [comment] 2018-04-12 08:29
> About the general removing of the final:
> That's more a question to the API design and grants.

My feeling about `final` for methods/classes in general : 
I spend lot of time developing plug-in for eclipse and I remember how painful it was to duplicate a lot of classes just because of a final keyword or a private/package modifier or an hidden OSGI package.
Even,  if we think this is not a good idea to override it, I would prefer to let user be able to do that and just add comments in javadocs to say this is not intended to be.
For private/protected package, I confess this is not so obvious as this commit us on a given API to maintain.
For final keywork on class and method, I feel this is rarely a good idea to use it.

**Comment by boaks** [comment] 2018-04-20 17:49
I'm not sure, if final is really overused in californium. I hope I didn't add too much, I usually don't use it.

But for the above concrete use-case, I'm still wondering, what really was intended to be achieved. Therefore I asked about the intentions. But unfortunatley, there is no answer until now.

**Comment by clementpellerin** [comment] 2018-05-07 15:59
My exact use case is to handle all calls programmatically so all paths should lead to the unique Root resource. I ended up implementing getChild() to return "this" as already mentioned. I dislike this work-around because it hides the true intention of letting findResource() always return the same root resource. Basically, after getChild() is called once, findResource() continues calling it mindlessly for all remaining parts of the path. This looping is what could make implementing some wildcards difficult. No matter what you want  your wildcard to do, you are forced to go through the remaining parts of the path.

In a more abstract sense, I think wildcards are a concept that belong to the whole path instead of the intermediate resource.

This all becomes irrelevant if the developer could override a non-final findResource().

If findResource() must remain final for some reason, then the javadoc should be updated because there is no way to change that code and therefore no way to implement wildcards there.

**Comment by boaks** [comment] 2018-05-07 16:48
Any snippet, how you want to implement your `findResource()`?

**Comment by clementpellerin** [comment] 2018-05-07 17:00
The method I need simply returns the root resource:
`protected Resource findResource(final List<String> list) { return getRoot(); }`
where getRoot() is a new accessor for the private field root which is not accessible in my hypothetical subclass.

**Comment by boaks** [comment] 2018-05-08 08:15
> If findResource() must remain final for some reason, then the javadoc should be updated because there is no way to change that code and therefore no way to implement wildcards there.

```
Searches in the resource tree for the specified path. A parent resource
may accept requests to subresources, e.g., to allow addresses with
wildcards like <code>coap://example.com:5683/devices/*</code>

```

So is your intention to use `coap://example.com:5683/devices/*` as URI in the request (really the `*`)? Do you have any information, that this is compliant to be used with CoAP? What do you expect as response?

Anyway, FMPOV, I don't see, that we should block that usage with `final`, 
even, if I can't see a general benefit. 

Any objection to remove the `final`?

**Comment by boaks** [comment] 2018-05-08 08:16
@sophokles73 
@sbernard31 

Any objection to remove the final?

**Comment by sophokles73** [comment] 2018-05-08 09:02
If the main concern is *inefficiency* of the *findResource* implementation in case of wild card resources then we could simply add the following to the loop in order to stop iterating over the (remaining) path segments:
```
	protected final Resource findResource(final List<String> list) {
		Deque<String> path = new LinkedList<String>(list);
		Resource current = root;
		while (!path.isEmpty() && current != null) {
			String name = path.removeFirst();
                        Resource child = current.getChild(name);
                        if (current == child) {
                           break;
                        } else {
			  current = child;
                        }
		}
		return current;
	}
```

would that solve your issue @clementpellerin ?

**Comment by boaks** [comment] 2018-05-08 11:52
Though I don't see, how the "root" Resource can be changed, it will not return itself in "getChild()".
The new issue #631 shows also some functional leaks. 
I'm not sure, if a small redesign is required to create "new resources".

**Comment by clementpellerin** [comment] 2018-05-08 13:40
@boaks, I do not intend to use wildcards. I bring the issue of wildcards simply because the javadoc claims something it cannot deliver unless we remove the final keyword.

@sophokles73, Your suggestion should be regarded as a new feature not an optimization since it slows down the usual case to speed up a case that almost never happens. I have a work-around, so I don't need this change. My issue is more conceptual. 

@boaks, my root resource is a subclass of CoapResource that overrides getChild() to return this. Maybe I should have shown that code snippet too.

It seems pretty obvious to me someone would want to override findResource() because they don't want to duplicate deliverRequest() in their preDeliverRequest(). I still don't see what is the big deal to remove the final keyword.

Remember, we really need the getRoot() accessor too to complete the solution.

**Comment by boaks** [comment] 2018-05-08 13:58
> I still don't see what is the big deal to remove the final keyword.

I agree, that it should not be a "big deal". 
Therefore I hoped, no one raise his objection, but ...

**Comment by sophokles73** [comment] 2018-05-09 10:38
> Your suggestion should be regarded as a new feature not an optimization since it slows down the usual case to speed up a case that almost never happens.

How so? My understanding is that it actually speeds up the rare case where a resource implements a (trailing) wildcard (e.g. /my/path/*) by returning `this` in the *getChild()* method but keeps the original behavior in case of normal hierarchical resources. We do not have a general concept of wildcards at all levels of the path.

In any case, I would not have a problem with a PR that removes the `final` keyword from *findResource* 
and adds a *getRootResource()* method ...

**Comment by boaks** [comment] 2018-05-09 10:58
> In any case, I would not have a problem with a PR that removes the final keyword from findResource
> and adds a getRootResource() method ...

Great! 
So @clementpellerin, do you have a ECA? If so, would you like to create a PR? 
If one of the answers is "no", I could prepare that PR next weekend.

**Comment by clementpellerin** [comment] 2018-05-09 12:51
@sophokles73 Again, I don't understand the justification because by definition, a trailing wildcard is last and therefore there are no remaining path parts to skip after it.

Maybe I'm wrong, but I thought there was no code in Californium to handle wildcards. This would be a strange exception for a very minor case. Wildcards are left as an exercise for the application developer and making findResource() non-final will help a lot.

I suggested the method name getRoot() because that's what the existing accessor is called in CoapServer. I think consistency is good and renaming/duplicating the accessor in CoapServer is unnecessary.

@boaks I signed the ECA but I am not familiar with git and especially pull requests. This is a trivial change. I would appreciate if you would do it for me. Thanks.

**Comment by sophokles73** [comment] 2018-05-09 13:59
When you register a resource in the resource hierarchy, say directly underneath the root resource, then the ServerMessageDeliverer's *findResource* method tries to find the resource that *feels responsible* for handling the request. A resource can indicate that it feels responsible for the request by returning `this` in its *getChild()* method. So, let's say that you want to register a resource that is responsible for handling the wildcard path `/first/*`. Then you can implement a resource with name `first` as described above and add it to the CoapServer using *add(Resource)*. Then, whenever a request is received with a Uri-Path that starts with `first`, your resource will be asked to return its child that is responsible for handling the next path segment. However, if your resource returns *this* then the search is over and the request is delivered to your resource for processing. You thus have effectively implemented the wildcard path `/first/*` ...

**Comment by boaks** [comment] 2018-05-09 14:58
@clementpellerin 

Please fetch 2.0.x, commit 3b70c546c, and check, if the `ServerMessageDeliverer` works now for you.

**Comment by clementpellerin** [comment] 2018-05-09 15:00
This is fine, but do you really want two naming conventions for CoapServer.getRoot() and ServerMessageDeliverer.getRootResource()?

**Comment by sophokles73** [comment] 2018-05-09 15:02
>  The loop stops immediately because it's the last iteration anyways.

That is only true for a request with a Uri-Path of `/first`, but not for a Uri-Path or `/first/second/third/fourth`.

**Comment by boaks** [comment] 2018-05-09 15:07
> but do you really want two naming conventions for CoapServer.getRoot() and ServerMessageDeliverer.getRootResource()?

Yes. So can I close this issue (again)?

**Comment by clementpellerin** [comment] 2018-05-09 15:10
@sophokles73 I would prefer if Californium did not incorporate that change, but its not my decision.

@boaks, yes, you can close the issue. Thank you.

**Comment by boaks** [comment] 2018-05-09 15:14
FMPOV, I'm pretty sure, that

https://github.com/eclipse/californium/issues/318#issuecomment-387335336

will not have any effect on the numbers. So, I would not change it.

**Closed by boaks** 2018-05-09 15:14 UTC
Labels: waiting for feedback
